### ISSUE TITLE
As a user, I need to keep track of my previous searches and assign names to them (named queries), so I can work on multiple sessions over time and find the results back

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#10]
As a user, I would like to be able to keep history of the queries I have made and store them, so I can keep track of my research and go back to previous search results per query.

Good example: Scopus database, medical databases (Ovid), Web of Science.

Other ToDos (user requests) not included as separate issues yet are:
-Store the query that was used for creating a specific list of bookmarks

**Comment by lilimelgar** [comment]
User request from evaluation: History of search results/how to go back to previous results?

See requirements specification document [here](https://docs.google.com/document/d/1nYUUdTfXyN0ANobe4AcrASPQWvh5-5YK7uWvw-7Q9r4/edit#).

**Comment by roelandordelman** [comment]
@lilimelgar I suggest to forget about the "named query", it's just a query logging mechanism that you want as far as I can tell. Or call it "saved query" (that scholars obviously can give a name, e.g., "my first query" ;))

**Comment by lilimelgar** [comment]
Updated in #336
