### ISSUE TITLE
As a scholar I want to be able to make multiple selections of terms per facet and across facets

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#107]
This issue is solved at the data level, on March 20, 2018, pending todo is to fix the interface in a way that the facets are not presented in tabs (users need to have an overview of how the data is updated in the different facets), in the style of zoeken.verteldverleden.org.

--
Users need to be able to select more than one term within a facet (OR operator), e.g.:
![screen shot 2018-02-12 at 17 04 56](https://user-images.githubusercontent.com/8133228/36106175-e8108ec2-1016-11e8-89fc-6fce62456709.png)

Also across facets (AND operator). The options of the facets get updated accordingly to the filtering choices.  

**This is a typical facet search functionality, similar to the faceted search provided in Zoeken.verteldverleden.org.** Terms inside the facets can be refreshed.

**Comment by roelandordelman** [comment]
@jblom this one seems to be missing

**Comment by jblom** [comment]
It already works like this. @lilimelgar can you confirm & close this issue?

**Comment by lilimelgar** [comment]
Tested in Master. Works well. Still pending for wrapping up work with facets: #358 (remove limit of 20 terms), #416 (adding ordering options and download button to facets)
