### ISSUE TITLE
As a developer, I need to implement a playout solution for B&G collection in two steps, so users can have access to the content of this collection

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#113]
1. Give computer (vpn) to scholars who need urgent access (short term). Scholars need to know very soon how to view the materials in order to work in their pilot projects ;)

2. Work on the [dev-plan](https://drive.google.com/open?id=1ghCiukem9crbMdD5_oS2ZQeWOaNnGvPWjowTQFYT5eY).

**Comment by jblom** [comment]
So the initial version of the secure play-out is available in the test environment. Moreover I requested two (sub)domains to be added to the DNS, which I can use to make the play-out accessible from the web.

When available we should plan a test round.

**Comment by lilimelgar** [comment]
@jblom Is it possible to test now?

**Comment by jblom** [comment]
we have to properly plan testing this. It's not only up to me in this case. Technically it is ready for testing (it's already used by the test environment, but you still need VPN).

**Comment by lilimelgar** [comment]
@jblom: happily B&G videos play from outside B&G and without VPN now (test July 16, and during summer school). Shall we close this Epic?

**Comment by jblom** [comment]
cool, yes let's close itttttt

**Comment by lilimelgar** [comment]
🥇
