### ISSUE TITLE
Field selector, or Multi-level search

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#12]
In the previous AVResearcher tool, users need to search for words in three types of fields:
(1) Title fields
(2) Description fields ("beschrijving" fields where archivists have entered manual descriptions"), in this way, scholars can analyse what terms are used by archivists in their descriptions, find content based on terms used in the summary/description fields
(3) Speech subtitle-related fields (content, what is being said, speech)

Equivalent in AVResearcher to the "metadata fields" selector (see new design proposal [here](https://drive.google.com/open?id=0B_Ld__Tb_1zWZHEyMDJ3Y2FpMFk).

The title field selector is also important to make more specific queries. For example: if you know that a video is called ["Vrouwen gaan stemmen" ](https://www.openbeelden.nl/media/976587/Vrouwen_gaan_stemmen_HD) and you want to find it in the Media suite search recipes, there should be a way to select the option: search in the title field only, otherwise, it is almost impossible to find it (perhaps also because of search-related issues).

**Old description:**
This component does not exist yet. 

The user should be able to select which field or group of fields should be used for the search (it is not the same as facets). For instance: search in the title, or search in the subtitles, or search in the descriptions (summaries). We had listed some more options in the design session in March [here](https://docs.google.com/document/d/1x4bS7HaNIwjkv1LMUJwetOgkj-ZwvtZxI90CrwQIg7Y/edit#bookmark=id.i2cbbjtg830l), in the “where to search” selector. Equivalent in AVResearcher to the "metadata fields" selector (see new design proposal [here](https://drive.google.com/open?id=0B_Ld__Tb_1zWZHEyMDJ3Y2FpMFk), but this should scale to encompass all collections in the MS).

User story 57: I want to be able to search on specific fields of television data (Description of item, title, tt888)

**Comment by lilimelgar** [comment]
Field clustering: Work in progress, added to my "user requirement analysis" list. We add this to Version 2.

**Comment by lilimelgar** [comment]
Related to issues #70 and #68

**Comment by jblom** [comment]
I've worked on this issue and it now works on the new search API, which works on Elasticsearch 5. After we've imported all collection data into this new version of ES. I can deploy this onto the test server.

**Comment by lilimelgar** [comment]
This was written on 17th Augusts:

Here some comments after testing it. 

I used two examples:

Example 1) Title: Stemmen verkiezingen. Date: 01-01-1922. Link
When I search for terms in the field “BG:description”, e.g., “Groepje menses waaronder moeders met kinderwagens”, using the current “Descriptions” cluster, results are not retrieved. I tried with and without quotation marks. It finds it if I use “Search: in all fields”.
Which fields are included as part of “Descriptions”? In AV researcher it is only “Beschrijving” (bg:description), but perhaps also “Samenvatting” (bg:summary) should be included?

Example 2) Title: De bende van Van der Lende. Date: 11-03-2014. Link
In this one I do find the result if I use terms from the “BG:summary” field ("Frank belt met Spike om te kijken wat zijn vetste festival”) 

Other issues:
-I could not find this item in any way: http://in.beeldengeluid.nl/collectie/details/expressie/4166590/false/true 
-Perhaps order by default using Relevance?
-The date picker (Github issue 97) has display problems, but it works correctly by typing the date manually

**Comment by lilimelgar** [comment]
Jaap's answer, 22 August:

today I worked a bit on these things you mention here:


I used two examples:

Example 1) Title: Stemmen verkiezingen. Date: 01-01-1922. Link
When I search for terms in the field “BG:description”, e.g., “Groepje menses waaronder moeders met kinderwagens”, using the current “Descriptions” cluster, results are not retrieved. I tried with and without quotation marks. It finds it if I use “Search: in all fields”.
Which fields are included as part of “Descriptions”? In AV researcher it is only “Beschrijving” (bg:description), but perhaps also “Samenvatting” (bg:summary) should be included?

>>>>> initially I only included bg:summary. Now the complete "field category mapping" is (avaible in the test environment):

{
				'id' : 'titles',
				'label' : 'Search in: titles',
				'fields' : [
					'bga:series.bg:maintitles.bg:title',
					'bga:season.bg:maintitles.bg:title',
					'bga:segment.bg:maintitles.bg:title',
					'bg:maintitles.bg:title'
				]
			},
			{
				'id' : 'descriptions',
				'label' : 'Search in: descriptions',
				'fields' : [
					'bg:summary',
					'bg:description',
					'bga:segment.bg:description',
					'bg:museum-description',
					'bga:series.bg:museum-description',
					'bga:segment.bg:museum-description'
				]
			},
			{
				'id' : 'subtitles',
				'label' : 'Search in: subtitles',
				'fields' : [
					'bg:transcripts.bg:transcript.bg:text',
					'bga:segment.bg:transcripts.bg:transcript.bg:text'
				]
			}

After this update I can find your example :)  



Example 2) Title: De bende van Van der Lende. Date: 11-03-2014. Link
In this one I do find the result if I use terms from the “BG:summary” field ("Frank belt met Spike om te kijken wat zijn vetste festival”) 


>>>>> I can find this example (after the update) too (both via the title or the summary in combination with the date)

 

Other issues:
-I could not find this item in any way: http://in.beeldengeluid.nl/collectie/details/expressie/4166590/false/true 

>>>> me neither, maybe it's not in the index. Wil have to check later.
 
-Perhaps order by default using Relevance?

>>>> should be like this right now...
 
-The date picker (Github issue 97) has display problems, but it works correctly by typing the date manually

>>>> this is ok now

**Comment by lilimelgar** [comment]
Ok. Next step is to implement this for the other collections as well @wmelder (mappings with Willem).
