### ISSUE TITLE
Graphs on comparative search don't render properly

### ISSUE THREAD

**Issue by avlisodraude** [CLARIAH/wp5_mediasuite#120]
When on the 'comparative-search' if a search more than 2 terms/collections once I start removing search queries the last two graph lines stay on view.
Normal behaviour (expected):
Every time I remove a search the graph should update to reflect the current selections.
To get a more clear picture the next short screencast will explain it better:
[video](https://drive.google.com/open?id=0B8StOK8IHMiQSjMyOTBsekZQX1E)

**Comment by jblom** [comment]
@lilimelgar this one is ready for testing

**Comment by lilimelgar** [comment]
Ok!
