### ISSUE TITLE
Removing last item from comparative search displays empty blocks

### ISSUE THREAD

**Issue by avlisodraude** [CLARIAH/wp5_mediasuite#121]
Where it happens? In Comparative Search recipe.
Issue: When selecting more than one query if we remove the first selected or at least not the last query. The queries in-between display empty blocks. The short screencast gives a better picture of this issue and how to reproduce it.
[Demo issue](https://drive.google.com/open?id=0B8StOK8IHMiQVzdMSWxVaDdhdjA)

**Comment by jblom** [comment]
I solved this issue on the master. I also solved another issue where sometimes the line chart is not updated correctly after deleting certain blocks (sometimes a line related to a deleted block would still be visible)

**Comment by lilimelgar** [comment]
Ok!

**Comment by jblom** [comment]
cryptic! 🔢
