### ISSUE TITLE
Date picker should adapt to existing data ranges

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#123]
In the date picker (Single collection search, Comparative search), it would be very useful and clear if the range offered in the default begin date (first date picker) and end date (second date picker) would adapt to the existing data ranges. Example: if a user selects using the date selector, the field "program=>bg:creation date (in:carriers)", the first date picker selects the earliest creation date, and the second date picker selects the latest creation date.

--Based on data available in date type field selected, update date picker with the date range available.--

![screen shot 2017-08-28 at 08 29 33](https://user-images.githubusercontent.com/8133228/29761751-177fb2ee-8bcb-11e7-8d5b-7cb8f96077b2.png)

This issue is related to #55 and #75

**Comment by avlisodraude** [comment]
@lilimelgar This issue has been done and committed. The code has been merged into the Master branch for the lab-components.

**Comment by lilimelgar** [comment]
The date picker is now getting empty values when a new type of date is selected. This may also be a good solution. I leave this issue open until we get more requirements, together with issue #125.

**Comment by jblom** [comment]
Hi again, I fixed this. Now whenever you the histogram is filled with something, the date pickers only allow you to select from that range. You can get back to other ranges by removing the date selection and/or other selections/filters/whatever. 

Ready for testing and in the master

**Comment by lilimelgar** [comment]
Tested in the Master, works well! We still need to improve the help text and summary numbers (#128) since it is not so clear yet... but this one is now solved/closed.
