### ISSUE TITLE
Add name of date fields that are used in result list

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#124]
Currently, users find a sorting button (Sort by date) to order results in the result list. However, since there are many date fields in the date selector to select from , it would be more clear if the mouseover text says which date is used for ordering.

![screen shot 2017-08-28 at 08 52 08](https://user-images.githubusercontent.com/8133228/29762319-3a73c210-8bce-11e7-817a-83c4514f20db.png)

**Comment by avlisodraude** [comment]
@lilimelgar  Issue solved in committed. Waiting for pull request to be merged into Master branch.

**Comment by lilimelgar** [comment]
Checked. Please add "Sort by" before displaying the name of the tag. E.g.:

Sort by Program=> bg: sortdate (in: publications)

**Comment by jblom** [comment]
check: added it to my master branch code. Will commit it later on

**Comment by avlisodraude** [comment]
@lilimelgar : This issue was solved. I just put it back into the testing column. The sorting should display correctly the "Sort by: <date-field-name>" as requested.

**Comment by lilimelgar** [comment]
Good! -tested on local server (master branch updated)
