### ISSUE TITLE
Add option to clear date filters

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#125]
Add a button for clearing date selections in the date picker, and go back to the initial default dates.

**Comment by jblom** [comment]
I worked on this issue and now it is possible to clear the selected date range. What needs to be done is to make it all look better, but it works:

![schermafbeelding 2017-09-26 om 17 31 11](https://user-images.githubusercontent.com/917310/30869085-99f72082-a2e0-11e7-8253-74ff788ccd71.png)

**Comment by lilimelgar** [comment]
It works well indeed. From the feedback received in the last workshop, users need also to be able to fix a date range for doing several queries within the same period, so they don't have to enter the dates every time. Shall I add this as a new issue?

**Comment by jblom** [comment]
this is indeed something for a new issue, since it might tie in with the user space or storing something in a user project (e.g. for project WWII I want to search all collections only between 40-45)

**Comment by lilimelgar** [comment]
Nice idea, this matches with one pilot request for doing this period-selection even from the Collection Inspector. Entered as issue #148 , and closed this one :)
