### ISSUE TITLE
As a user, I would like to see what is the name/label of date field used in the resource viewer, so I can distinguish between different types of dates

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#126]
Currently, the resource viewer (detailed information per record) shows a standard "Date" label. Since there are many dates used in the MS, it would be useful to indicate (on mousover) which date field is being picked here.

![screen shot 2017-08-28 at 09 50 31](https://user-images.githubusercontent.com/8133228/29764152-5fb70494-8bd6-11e7-8b24-c8e147f279ab.png)

**Comment by roelandordelman** [comment]
@avlisodraude did you deploy on test? I don't see something there

**Comment by lilimelgar** [comment]
I tested in master (updated Jan.24) with several collections, the icon for the tooltip shows in the resource viewer, but the date does not show on mouse over.
![screen shot 2018-01-24 at 08 37 22](https://user-images.githubusercontent.com/8133228/35319885-0d4f5ca2-00e2-11e8-944f-6f717ccc5b44.png)
@avlisodraude please let me know if I am missing some update of the master (did npm run prod in labo and ms).

**Comment by jblom** [comment]
@lilimelgar please test this on the test server. I'll send you the updated mappings, so you can also see the date field on master
