### ISSUE TITLE
Search button in query box does not work

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#129]
When entering a query term in the query box, hitting the enter key produces the expected result list, but the query button (magnifying glass icon), red arrow, does not work:

![screen shot 2017-08-29 at 13 20 33](https://user-images.githubusercontent.com/8133228/29818537-0b95ad60-8cbd-11e7-84c0-e2942c4297a5.png)

**Comment by avlisodraude** [comment]
Issue done and code committed. Just waiting too be merged with Master branch

**Comment by lilimelgar** [comment]
Ok
