### ISSUE TITLE
Remove "collection metadata" tick box from current search interface

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#130]
The "Collection metadata" tick box below (red arrow) should be hidden in the interface, at least until we can provide more options (layers) later:

![screen shot 2017-08-29 at 13 24 41](https://user-images.githubusercontent.com/8133228/29818618-74620bcc-8cbd-11e7-80cf-b18c555119f5.png)

**Comment by avlisodraude** [comment]
@lilimelgar  Done and ready for merge to master
