### ISSUE TITLE
Change current collection name label for CKAN label

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#131]
Currently, the Single and Comparative search recipes display a label for the collection which is not user friendly (example: "nisv-catalogue-aggr" below):

![screen shot 2017-08-29 at 13 34 17](https://user-images.githubusercontent.com/8133228/29818952-cbfe5880-8cbe-11e7-8a72-8f7355a7c693.png)

It is suggested to add a more user friendly label, for instance, the value "title" of the collection.

This is the same label that shows in the collection selector:

![screen shot 2017-08-29 at 13 38 19](https://user-images.githubusercontent.com/8133228/29819076-59b2885e-8cbf-11e7-9d95-2cef5b707275.png)

This issue is related to #128

**Comment by lilimelgar** [comment]
This currently works OK in the Single collection search, but not in the Comparative search recipe.

**Comment by avlisodraude** [comment]
This issue has been solved for both single and comparative search. The changes are already available to be tested in the Master branch. 
<img width="1088" alt="screen shot 2017-11-06 at 11 56 32" src="https://user-images.githubusercontent.com/5918438/32438133-c1b7168a-c2e9-11e7-86d2-eeb9f383f271.png">

**Comment by lilimelgar** [comment]
Great! tested
