### ISSUE TITLE
Update search results when field cluster selector is applied in query builder

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#132]
When building a query, a field cluster can be selected as filter. The "search in: all fields" cluster is selected by default. When the other options are selected (i.e., "Search in: titles", etc.), the total of found media objects should be updated, and also the result list.

![screen shot 2017-08-29 at 15 07 45](https://user-images.githubusercontent.com/8133228/29822482-eeb50e0c-8ccb-11e7-9d4a-20e7edf84991.png)

This was working properly in the test version before August 29.

**Comment by avlisodraude** [comment]
This issues has already been solved by @jblom .
It will testable once the branches are merged (most probably today)

**Comment by lilimelgar** [comment]
OK :)
