### ISSUE TITLE
Hide metadata layer selector from the Single Collection search recipe

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#137]
Please hide this tick box for now:

![screen shot 2017-08-31 at 15 03 28](https://user-images.githubusercontent.com/8133228/29924539-93131d12-8e5d-11e7-99cc-b60c70fc8840.png)

**Comment by avlisodraude** [comment]
@liliana duplicated issue :-)

**Comment by lilimelgar** [comment]
same as #130
