### ISSUE TITLE
Change the label of the Multi-layered single collection search recipe

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#138]
Change the name of this recipe to "Single Collection Search" in the [recipes general page](http://mediasuite.clariah.nl/recipes), and in the [recipe's page](http://mediasuite.clariah.nl/recipe/single-search).

**Comment by avlisodraude** [comment]
Done and pushed to master branch in Mediasuite project

**Comment by lilimelgar** [comment]
Done
