### ISSUE TITLE
Change field groups red labels in the Collection inspector recipe (metadata inspector)

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#141]
In the metadata inspector icon of the Collection inspector recipe:

Change the red labels (headers) in the metadata inspector into something more meaningful for scholars.

![screen shot 2017-08-07 at 16 21 39](https://user-images.githubusercontent.com/5918438/29031119-729cc5e8-7b8d-11e7-832b-d4696507777a.png)

This is a suggestion to change the labels:
-  "Fields of type: date" : Metadata fields to specify dates
-  "Fields of type: string": Metadata fields that can be used to create facet search (filters)
-  "Fields of type: not_analyzed": Metadata fields that are not indexed (used for display only)
-  "Fields of type: long": Metadata fields that indicate duration

These names have to be confirmed with @jblom before.

**Comment by jblom** [comment]
I've worked on this issue and now the different field types are described as follows: 

![schermafbeelding 2017-09-26 om 13 28 52](https://user-images.githubusercontent.com/917310/30858239-1e932c72-a2bf-11e7-9bdf-5a67018deb99.png)

I've also gotten rid of the meaningless document types (consistent with removing the document type selection in the collection inspector)

We should work a bit more on the texts, to make it as user friendly as possible. Let's consider this an intermediate solution

**Comment by lilimelgar** [comment]
Good! Things to improve include help menus/texts, and user friendly labels (at least for B&G collection is work in progress).

**Comment by jblom** [comment]
ok check
