### ISSUE TITLE
As a user, I need to see the metadata in a transparent but also user-friendly and documented way

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#142]
This Epic includes issues of metadata transparency and user-friendliness of metadata labels.

**Comment by jblom** [comment]
adding @mwigham 's description from the duplicate/closed issue here:

"The user needs to select metadata fields while searching, or defining visualisations. What is understandable and relevant depends on the user and the particular task they are carrying our. For example, one user may be content with searching on 'date', while another may want to determine a specific type of date field to search on (e.g sortDate). The user should be offered the choice between simplified/aggregated fields, or more specific, with documentation on the fields to help them choose.

Deliverable: Metadata field selector in the Media Suite that allows users to choose different levels of metadata fields, and to browse documentation of the fields. Acceptation criteria: Media suite user finds it easy to use, and it helps them in their choice of metadata field."
