### ISSUE TITLE
Add option to combine clusters in field cluster selector

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#144]
This issue is to improve the field selector feature that is used by the Single Collection Search and Comparative Search recipes:

![screen shot 2017-10-03 at 09 52 48](https://user-images.githubusercontent.com/8133228/31114937-a4bd11bc-a820-11e7-8ee1-eb4dfa51b02d.png)

In the new designs suggested to improve this functionality (see image below), there are tick boxes to select one or more field clusters. That is the improvement requested in this issue.

![screen shot 2017-10-03 at 09 54 50](https://user-images.githubusercontent.com/8133228/31115023-f368ce0a-a820-11e7-9456-9b817d1620a4.png)

**Comment by jblom** [comment]
@lilimelgar this is ready for testing

**Comment by lilimelgar** [comment]
OK! works nicely, we should add mouse over instruction later on (took note of this for later). Tested in Master branch.
