### ISSUE TITLE
Change "Select field" default option to date field selector

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#147]
Currently the date field selector (image below) used by the Single collection and Comparative search recipes chooses "Sort date" by default (for B&G collection). Include the option "No date field" (or "Any date field", or "Select field") at the top of the drop down list, and show that one by default, so users are aware that they will have to select a date field here.

![screen shot 2017-10-03 at 11 01 03](https://user-images.githubusercontent.com/8133228/31117476-37269c22-a82a-11e7-9cf0-1fddde45b318.png)

When the date range is cleared (implemented from issue #125), the default date field should go back to the default option.

**Comment by jblom** [comment]
@avlisodraude fixed this and is now also available on test (and in the GH master)

**Comment by avlisodraude** [comment]
@lilimelgar I just moved this issue to the testing column since it's been already solved as Jaap mentioned.

**Comment by lilimelgar** [comment]
Good! tested on B&G collection Single and Comparative search (master branch).
