### ISSUE TITLE
As a scholar, I would like to be able to send repetitive queries within the same selected date range, so it is easier to focus on a specific period for my research

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#148]
Some users search only in the same time periods repetitively. For these users, it is common to do several queries within the same date range. The date range selected with the date picker should then remain the same. 

At the moment, there is an X option added to date range in order to clear the dates (issue #125), perhaps add another symbol that indicates that the date range will be frozen for the next query.

**Comment by avlisodraude** [comment]
@jblom:
Just to set it as default in newSearch() (L:211) replace null value from line 211 to this.state.selectDateRange. This will make any new query keep the date range and the user could click the already set close btn to remove dateRange data.

**Comment by jblom** [comment]
now the selected date range and field cluster stick, meaning it won't change after entering a new search term. This can now be tested on test

**Comment by lilimelgar** [comment]
Tested in Test version (June 20) with B&G (av, radio, tv), Desmet papers, Open images (EYE, B&G), DANS OH. All OK :)
Not tested with Desmet films, Desmet posters == no date field available
Not tested with KB newspapers == pending to test (because of slow search, one cannot select start and end time, which results always in "invalid date"

@lilimelgar: test when KB and Desmet films/posters ready

**Comment by lilimelgar** [comment]
Tested with all collections (except Desmet posters=no date yet) on production version July 16. Done!
