### ISSUE TITLE
Implement bookmarking functionality in result list (quick annotation)

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#15]
As a user, I need to select items for building my corpus.

Add bookmarking functionality to search results: A user can select/mark items from a search result list in three ways: 
(1) manually via the resource viewer (implemented in version 2)
(2) manual, by for instance ticking a box next to each search result, 
(3) all the result list from a query/result list (this is related to the save queries request: issue #10). 

Priority for V3: (2) and (3). See design ideas [here](https://docs.google.com/presentation/d/1mQl28c92gW2SDJn2kAYJEhn6_dzEiGGMHR7fx_pdpYk/edit#slide=id.g2fa8d09fe6_0_71)

**Comment by jblom** [comment]
Alright, I've updated the master and the test environment with my latest additions regarding this issue. I've basically (re)implemented (1) and (2).

(3) saving loads of bookmarks and/or saving an entire query I'd rather see in a different issue, so we can plan work on that after (1) and (2) have been tested properly.

Also everything related to updating the UI/functionalities of the bookmark-centric & annotation-centric views should be moved in separate issues and still need to be done.

**Comment by lilimelgar** [comment]
I tested in Master (updated Jan.24), used all collections, functionality for 1 and 2 works very well! 👍. it will only get better after further user testing, improvements will be added as new issues. In relation to (3): issues about "bulk" bookmark related to saving queries will be added to Epic #10.

**Comment by jblom** [comment]
good to hear! Yes we need more iterations (also looking at the workspace more closely) to make it really interesting
