### ISSUE TITLE
Bring the histogram visualization outside the facet selector region

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#150]
Currently, the Single Collection and Comparative Search recipes include a histogram visualization in one of the facets (Uitzenddatum for B&G collection):

![screen shot 2017-10-03 at 12 10 30](https://user-images.githubusercontent.com/8133228/31120214-ea67fe9e-a833-11e7-918c-02197c039d1d.png)

A user request indicates preference for having this visualization outside this facet region, since users have to click on the tab "uitzenddatum" (or to any other field selected as date field) to see this visualization.

**Comment by jblom** [comment]
@avlisodraude & myself fixed this and it is now available on test (and in the master)
I'd say check it out

**Comment by lilimelgar** [comment]
Tested on Master, works well, but @avlisodraude: there are display problems: In the Comparative search, the histogram appears in the small grayed box, overlapped with all the facets and the timeline chart. 

![screen shot 2017-11-09 at 11 25 02](https://user-images.githubusercontent.com/8133228/32600749-e548ade4-c540-11e7-9375-87d03e6213d6.png)

Perhaps, a way to fix this could be to move the histogram to the region outside the grayed area, adding a header: "Search results plotted on a histogram chart", and add the query number as a title to the histogram, in the same way that the Timeline chart is presented now.

**Comment by jblom** [comment]
the overlapping is already fixed (if you were testing locally, make sure to "npm run watch" the wp5-mediasuite code as well, otherwise the styling is not updated properly)

As to moving the histogram outside of the grey box: where would it need to go? There is a histogram for each query... It's better to wait for FW to come up with a design for this.

**Comment by lilimelgar** [comment]
Tested in Master and test version. Ok (histogram outside facet area and overapping solved). We discuss later the idea of bringing it outside the grey box with Werner. Closed for now.
