### ISSUE TITLE
Enable search in the Collection selector

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#153]
Currently, the Collection selector component provides a drop-down list with the names of the collections + a tiled display of collections with icons and information snippets:

![screen shot 2017-10-05 at 14 45 08](https://user-images.githubusercontent.com/8133228/31227912-d6b0f064-a9db-11e7-9bfd-82c9659260a7.png)

The request is to provide a search button to query these collections by using the same search facilities provided by CKAN (i.e.,: tags, organizations, groups, name/title).

**Comment by avlisodraude** [comment]
@lilimelgar : Issue solved and merged with Master. Ready for testing :-)

![screen shot 2017-11-13 at 17 19 28](https://user-images.githubusercontent.com/5918438/32736079-e14fd362-c896-11e7-9881-386a8ab7653b.png)

**Comment by lilimelgar** [comment]
This issue is partially solved: the search bar offers the option to search by title of the collection. This is tested (master branch). 

However, the requested "search" facilities in the collection selector include much more: using tags, organizations, formats, licenses, etc., as in CKAN (http://mediasuitedata.clariah.nl/). But this was too much for an issue... we can wait for Werner´s work of rebuilding the Collection selector according to new designs, I close it for now.
