### ISSUE TITLE
Add time line chart to the Single Collection search recipe & switch button between types of graphics

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#155]
This visualization (time line chart) is only available in the Comparative search recipe. 

![screen shot 2017-10-12 at 16 04 22](https://user-images.githubusercontent.com/8133228/31500195-14984694-af67-11e7-8577-52b7caeb7828.png)

This user request is to also add this component to the Single Collection Search recipe.

Besides, the request is to merge the histogram visualization (bar chart) with the time line chart graphic, and add an option to switch between the two types of graphics. 

This is to be done in the Single search and Comparative search tools. Another issue will be opened for the Inspector graphic.

Merged with #150

**Comment by avlisodraude** [comment]
@lilimelgar Changes already can be tested in the mediasuite:
http://mediasuite.clariah.nl/tool/single-search?fr=0&sz=20&cids=nisv-catalogue-aggr&sf=&st=ede&dr=bg:carriers.bg:carrier.bg:creationdate__null__null&s=_score__desc&sl=nisv-catalogue-aggr

**Comment by lilimelgar** [comment]
Ready, tested on production version (v2).
