### ISSUE TITLE
As a scholar, I need to be able to switch on/off the display of "reruns" in the aggregated visualization of search results, so I can have a more accurate quantitative analysis

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#157]
This issue could be solved in an easy way by providing information (static text with updated number) of reruns in the total results for the query (related to issue #128). 

--
OLD
Note: this issue requires more clear requirements. 

The request is to offer an option to exclude/exclude "reruns" in the display of search results in the timeline chart. This applies to broadcast materials only (B&G collection). A "Rerun" is a program that has been broadcasted more than once.

Initial ideas sketched here by Jaap:
![img_20171010_115802041-1](https://user-images.githubusercontent.com/8133228/31504972-12743190-af74-11e7-8053-1250e7fc440e.jpg)

This issue is related to #136.

**Comment by jblom** [comment]
@lilimelgar marked this CLARIAH+ for now. Could maybe still be done, but has a very low priority for now

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #132](https://github.com/beeldengeluid/labo-components/issues/132) via [**ZenHub**](https://www.zenhub.com/)
