### ISSUE TITLE
Change help text in the "Comment" tab of the Annotation tool

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#158]
Currently, when users click on the "Comment" tab of the annotation tool, they get a help-text: "Add one or more tags". Since "Tags" are using for classification purpose, not for comments, please change this help text for "Add one or more comments or notes".

![screen shot 2017-10-16 at 15 43 32](https://user-images.githubusercontent.com/8133228/31615196-21dc8250-b289-11e7-8fcc-3ac816386379.png)

**Comment by jblom** [comment]
this one should now work on the production version. You might need to clear cache.

**Comment by lilimelgar** [comment]
Great! thanks :), is it also fixed in the master? if so, please have the pleasure to close the issue ;)

**Comment by jblom** [comment]
yes it is also fixed on the master, which is active on the test environment. Close it!!! ^^
