### ISSUE TITLE
Change item ID for title in the annotation tool

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#159]
Currently, the annotation tool displays the media object ID:

![screen shot 2017-10-16 at 15 51 30](https://user-images.githubusercontent.com/8133228/31615517-1aa698da-b28a-11e7-9abd-deb601a77a19.png)

The request is to change that for the title of the media object.

**Comment by jblom** [comment]
Unfortunately this one is not easy to fix, since the title is not stored in the annotation... Have to look at this one later!

**Comment by lilimelgar** [comment]
Ok. We keep it open for later ;)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #144](https://github.com/beeldengeluid/labo-components/issues/144) via [**ZenHub**](https://www.zenhub.com/)
