### ISSUE TITLE
Browser fails when user press "Add" without adding a tag

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#160]
There is a bug in the annotation system. When I press 'Add' without entering a tag, the browser fails; after which the previously entered annotations are lost. This happens in the annotation component, custom tag. Tested in Chrome. See screenshots for clarity in the Gitter room, September 19: https://gitter.im/CLARIAH-media-studies/Tools-recipes

**Comment by jblom** [comment]
I fixed this now in the master. It was a silly little bug

**Comment by lilimelgar** [comment]
Solved :)
