### ISSUE TITLE
As a scholar I want the result list and the resource viewer to clearly show me if an item is playable / viewable or not

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#165]
Not all items/records in the Media Suite may be viewed/accessed/played because of several reasons. All records in the Media Suite should should have metadata indicating whether or not it is possible to access to content. This metadata should be presented in different ways, as added in the issues to this Epic.

**Comment by roelandordelman** [comment]
@lilimelgar : maybe I do not understand correctly but based on the two requirements you put earlier:

-----------------
1. In the result list (now the media icon type is shown when the media file is available, but it does not show any icon when this is not the case: perhaps show the same icons, but with a cross line when the media type is possible to detect in other ways, but the media file is not available, or a generic "no access" icon when the media file is not available)

2. In the Resource viewer, show more details about the possible reason why the media file is not viewable/playable. Examples:
B&G collection, ID: 215557
B&G collection, ID: 215532
-----------------

I would put as a story: As a scholar I want the result list and the resource viewer to clearly show me if an item is playable / viewable or not

**Comment by lilimelgar** [comment]
Tested in Master (March 28) with all collections (except KB newspapers -not available). The icons show now:
-Media type, or a question mark when not automatically detected
-An eye, open or closed if the item can be played/viewed

An issue still remains: the objects of type image/photo from B&G collection show an open eye, but there is no resource. Added as new issue: #351. Also added #352 about filtering options based on these icons/data.
