### ISSUE TITLE
As a user, I would like to see an updated list of available collections in the Collection selector, so I can use them for search or inspect

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#166]
Update the test version Collection selector to leave only the icons of collections that are available and include the new ones? (Kb, OH, program guides -this one not sure)

**Comment by lilimelgar** [comment]
This was done manually for releasing version 2, this issue is to add the correct tags in CKAN for automatic display of collections in the Collection selector.

**Comment by roelandordelman** [comment]
As the EPIC of this issue will be closed tomorrow, please rephrase (as a scholar...) and add to other EPIC

**Comment by jblom** [comment]
@wmelder in order for me to finish this, I need admin credentials for CKAN, so I can check the tags.

**Comment by jblom** [comment]
@lilimelgar @roelandordelman alright so now I implemented it like this:

when a collection has the tag: "clariah_media_es_indexed" it is considered by the search/collection API as a media suite collection. Subsequently the system checks if the index exists (by using the ID of the collection or directly via a custom CKAN field that uses es_index as the key and the name of the index as the value)

Anyway this has been implemented locally and works. I'll deploy this in test in a bit. 

After that what remains is some kind of timer (cron job) that checks CKAN occasionally for updates.

**Comment by lilimelgar** [comment]
I tested in Master (Feb.5) but I don't see it implemented locally yet ;)

**Comment by jblom** [comment]
@lilimelgar the implementation is on the search API side. If you use the test search API, it should work

**Comment by jblom** [comment]
@lilimelgar could you please test and close this one?

The thing that is not implemented is periodically refreshing the list of collections by scanning the CKAN API, but this could be placed in another issue (I think this issue was not created yet by me)

**Comment by lilimelgar** [comment]
I tested on Master, all collections' names and organizations are updated from CKAN, except one:
http://mediasuitedata.clariah.nl/dataset/open-beelden-beeldengeluid. In this one, the organization name should be Netherlands Instituut voor Beeld en Geluid (Varios creators).
![screen shot 2018-02-15 at 11 28 26](https://user-images.githubusercontent.com/8133228/36251964-5e9d60a0-1243-11e8-9a90-a95ab63ef144.png)
![screen shot 2018-02-15 at 11 28 48](https://user-images.githubusercontent.com/8133228/36251983-6e46bdc6-1243-11e8-920f-2a672ae5bcb5.png)

One question, please: do the icons/logos can also be included in the automatic update? Users have requested in the evaluation to have the logos back ;), since they helped them to identify the collections better. I added this to the issue you mention above.
#322.
