### ISSUE TITLE
Order alphabetically the list of metadata fields

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#170]
The list of date fields that is provided now in the Date picker (date field selector) is partially ordered alphabetically. Please check why the order is not done alphabetically:

![screen shot 2017-11-10 at 12 48 02](https://user-images.githubusercontent.com/8133228/32657305-8cf03498-c615-11e7-85b8-09791fe3701c.png)

**Comment by avlisodraude** [comment]
@lilimelgar This issue has been solved and merged into the Master branch. 

<img width="694" alt="screen shot 2017-11-13 at 11 43 48" src="https://user-images.githubusercontent.com/5918438/32724840-242daa8e-c873-11e7-98b2-c85ed64e6d45.png">

**Comment by lilimelgar** [comment]
Tested in Master branch. Only solved partially (it works well in Collection Inspector (selecting fields for X and Y axes), but not in the search tools (Single search and Comparative search) when you add a New facet:

![screen shot 2017-11-14 at 08 07 42](https://user-images.githubusercontent.com/8133228/32767309-18703d56-c913-11e7-9d62-8e43bf7e7064.png)

**Comment by jblom** [comment]
I solved this in the master @lilimelgar you can test it

**Comment by lilimelgar** [comment]
Tested, OK.
