### ISSUE TITLE
Implement custom workflow for incorporating subtitles in B&G collection

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#172]
After approval by Roeland, incorporate subtitles to programs. This was part of the previous AVResearcher tool.
Solution/workflow proposed by Willem:
![img_20171115_165200501](https://user-images.githubusercontent.com/8133228/32845966-66bb1c4c-ca26-11e7-80ac-626575b8f2d4.jpg)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-importer #5](https://github.com/beeldengeluid/labs-importer/issues/5) via [**ZenHub**](https://www.zenhub.com/)
