### ISSUE TITLE
As a developer, I need to detect what is the cause of missing segments in current B&G collection, so I can provide full access to the metadata of this collection

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#173]
There are missing segments in the current dataset (B&G collection), examples:

1) All the segments (items) from the Integrale uitzending "Sport in Beeld (NTS)" from 23-02-1964.
--ID of the entire program (as it appears in the Media Suite): 215557@program
--ID of the six missing segments (taken from Immix intern): 
50014 (Atletiek: Maple-Leafloop, te Hilversum"
50013 (5. Nationale dameskampioenschappen schermen floret, in Den Haag)
50012 (Zaalhandbal: Operatie '55...)
50011 (Biljarten: Europese kampioenschappen bandstoten...)
50010 (Voetbal: Velox -SHS...)
50009 (Voetbal: ADO -Sparta...)

2) Segments (items) from the integrale uitzending "Sport in Beeld (NTS)" from 06-09-1964
--ID of the entire program (as it appears in the Media Suite): 215532@program
--ID of the two missing segments (items, taken from Immix intern)
50378 (Voetbal: Ajax - regerend landskampioen...)
50379 (Voetbal: PSV - Go Ahead...)

**Comment by lilimelgar** [comment]
This is the message from Dani: http://oaipmh.beeldengeluid.nl/oai?verb=GetRecord&Identifier=oai:segment:174437&MetadataPrefix=bg

<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
    <responseDate>2017-11-15T13:07:32Z</responseDate>
    <request verb="GetRecord" identifier="oai:segment:174437" metadataPrefix="bg">http://oaipmh.beeldengeluid.nl/oai?verb=GetRecord&amp;identifier=oai:segment:174437&amp;metadataPrefix=bg</request>
    <GetRecord>
        <record>
            <header>
                <identifier>oai:segment:174437</identifier>
                <datestamp>2016-10-11T17:24:26Z</datestamp>
            </header>
            <metadata>
                <bg:bgelement xmlns:bg="http://oaipmh.beeldengeluid.nl/basic" xmlns:bga="http://oaipmh.beeldengeluid.nl/aggregated" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" aggregationType="segment" id="174437">
                    <dc:identifier>174437@segment</dc:identifier>
                    <dc:relation xsi:type="dcterms:URI">http://in.beeldengeluid.nl/collectie/details/expressie/215557/false/true</dc:relation>
                    <dcterms:isPartOf xsi:type="dcterms:URI">http://oaipmh.beeldengeluid.nl/resource/program/215557?output=bg</dcterms:isPartOf>
                    <bg:external-id>50011</bg:external-id>
                    <bg:maintitles>
                        <bg:title>SPORT IN BEELD</bg:title>
                    </bg:maintitles>
....
...
red line relates segment to parent program
met vriendelijke groet,

Danny Sedney
A-Team Software Development

**Comment by wmelder** [comment]
OAI-PMH does provide the right metadata record when requesting using GetRecord and identifier. Looked into it with Danny Sedney. Didn't find a problem. What happened earlier might be that I entered the wrong ID.

**Comment by wmelder** [comment]
Related to the issue that the NISV collection metadata needs integrity tests.
We need to inspect if something went wrong with the aggregated index creation by counting programs, series, seasons,  segments and detect orphans.

**Comment by wmelder** [comment]
I suggest to reinitiate a new harvest and compare final counts for segments, seasons, series and programs with the current basic index.

**Comment by mwigham** [comment]
See test plan https://docs.google.com/document/d/1HPat9CKJVyxD5Hz1nXA-PtbzURODu8RXdjPZOzvx0ag/edit?usp=sharing

**Comment by mwigham** [comment]
The segments are all present in the basic index (for information, here is the Elastic Search query used to find the six segments for the first example)
{
    "query": {
        "match" : {
            "dcterms:isPartOf.dc:identifier" : {
                "query" : "215557@program",
                "operator" : "and"
            }
        }
    }
}

**Comment by mwigham** [comment]
Found specific difference between ES query of index and search API #427

**Comment by jblom** [comment]
@lilimelgar @mwigham @wmelder this was already solved right?

**Comment by mwigham** [comment]
@jblom Yes, this is now solved
