### ISSUE TITLE
Eliminate numbers from timeline chart legend

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#175]
In the Collection inspector, timeline chat, there are numbers appearing in the legend (on top of the chart, in green and orange) which are not clear:
Total **0**, Missing **1**, Present **2**. Please delete 0, 1 and 2.

![screen shot 2017-11-15 at 18 52 14](https://user-images.githubusercontent.com/8133228/32852160-6cabb89e-ca37-11e7-800a-b2b46bffe0ac.png)

**Comment by jblom** [comment]
I removed them. Somehow the list index was added to the name. It's in the master only

**Comment by roelandordelman** [comment]
is this one still in review??

**Comment by roelandordelman** [comment]
Seems to be fixed so closing this one
