### ISSUE TITLE
As a scholar I want to use enrichment services available in the MediaSuite, so I can do my research based on the content (spoken word) of audio-visual sources

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#177]
In this epic we make a start with connecting enrichment services to the Media Suite workflow. We assume that enrichment services can only be accessed in the Work Space and at first, only on private collections (uploaded to the MS). Later we may allow scholars to select infrastructure data (e.g., NISV collection) and to send it to an enrichment service. Probably, this level of using enrichment services will be postponed to CLARIAH-PLUS.
   
The (simplified) use case we work on for version 3 is to provide automatic speech recognition as enrichment service for private collections that have been uploaded to the Media Suite personal workspace. We assume that this use case is particularly suited for Oral History scholars.

For this EPIC we need:
- stories on collection upload
- stories on the development of ASR as a service (already deployed in an NISV pipeline)
- stories on activating ASR in the MediaSUite workspace
- stories on using the ASR transcripts (indexed) in the workspace

(RO: below is not for this epic)
These are the custom ASR user requests from pilot projects:
-ASR for TV & Radio in period of interest (1945- to date) and specific genres (WW2 documentaries and selected broadcasts)
-ASR for TV & Radio in period of interest (1945 to 1990)
-ASR for TV (B&G) in period of interest (1960 to 1990) for documentary films

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-user-space-api #5](https://github.com/beeldengeluid/labs-user-space-api/issues/5) via [**ZenHub**](https://www.zenhub.com/)
