### ISSUE TITLE
As a user, I need to have a clear overview of what data/collections are available via the MS, so I can select the most relevant ones for my projects

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#184]
As a developer, I want to implement the wireframe for the [Collection page and Collection selector](https://www.figma.com/proto/yFjso1GQlHi3JkSXXKwabK/MS-Wireframes-v3?scaling=min-zoom&node-id=250%3A11676&redirected=1) of the Media Suite since it enables a better user experience with the CKAN registration system and supports users in identifying relevant datasets.

**Comment by roelandordelman** [comment]
After sprint #1 this epic will either be closed or redefined.

**Comment by lilimelgar** [comment]
@roelandordelman It will be redefined in the context of a plan for improving the task workflow of the MS. Moved to Icebox for now until plan is clear.
