### ISSUE TITLE
Create a way to distinguish different types of data layers according to their origin

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#185]
As a product owner and developer, I need to offer a solution to distinguish the different types of data depending on the way they originated: archival metadata, automatic metadata (enrichments such as ASR, subtitles), or user-provided metadata (via user annotations or crowdsourcing). This is what we called the "layered" approach in implementation of version 1.

**Comment by roelandordelman** [comment]
why is this in the review/QA? What's the question and to whom is it addressed? I assume after addressing it, this issue can be moved again to new issues?

**Comment by lilimelgar** [comment]
This issue is in review since we had to discuss how to do this. But Jaap has already provided an idea/solution:
-We index the string fields (archival metadata) and any other content field (ASR) as faceted fields, that is, by word frequencies. This enables users to visualize those frequencies for instance as word clouds. I move this issue to "in progress", since we still have to discuss the details & more concrete issues to achieve this. @roelandordelman

**Comment by lilimelgar** [comment]
Merged with #151
