### ISSUE TITLE
As a scholar, I need to search and have access to the KB newspapers dataset via the MS, so I can do comparative media analysis with other collections

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#188]
As a developer, I want to harvest the newspapers' dataset of the KB to make it available into the media suite.

-using the same facets as in Delpher (#104, replaced by #326)

**Comment by wmelder** [comment]
85% of the newspapers from the Kranten set is processed.

**Comment by wmelder** [comment]
kb is ready. in totaal 17,401,954 documenten. da's iets minder dan de vorige keer (21,480,148), terwijl er wel meer kranten in zitten 399318 vs 352831. Toch ga ik de oude index maar weggooien en een alias aanmaken verwijzend naar de nieuwe (kb-newspaper-test)

**Comment by lilimelgar** [comment]
Great news! 

I will test and add issues (if there are) to this epic before closing it.

**Comment by roelandordelman** [comment]
I'm using http://0.0.0.0:5304/recipe/single-search?cids=kb-newspapers
that shows: Total amount of records in this collection: 17401954 
However, search is not working yet.

**Comment by lilimelgar** [comment]
Dataset integrated in Version 2. Issues for improvement will be added separately.

**Comment by wmelder** [comment]
By mistake the harvesting process was run without apikey, therefor no newspapers after 1945 were indexed. Importing process is restarted with apikey, so now we expect also all available newspapers after 1945 to be indexed. The first 3000 or so are already added, so it's working! Processing all might take some weeks.

**Comment by lilimelgar** [comment]
Great! 
just to be sure, perhaps issue #104 may be important to take into account in the importing/mapping?

**Comment by wmelder** [comment]
Current import stops on an OCR document that is not available because of permission rights.
TODO: 
- [ ] update the resolve document method so that it uses basic authentication.
