### ISSUE TITLE
As a user, I need to get access to the complete metadata of the B&G audio-visual collection via the MS

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#189]
dito

**Comment by lilimelgar** [comment]
Datasets are integrated in version 2.

**Comment by lilimelgar** [comment]
There is one pending issue in this Epic, so it is reopened.

**Comment by lilimelgar** [comment]
@mwigham, @wmelder or @jblom: Can you please check if the issues in this Epic are solved and if it can be closed? Thanks.

**Comment by jblom** [comment]
I'd say yes

**Comment by lilimelgar** [comment]
👍
