### ISSUE TITLE
As a user, I would like to be able to use the Media Suite even if I don't have a university account in The Netherlands, at least with the open collections

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#200]
This epic includes issues to change the logics of the login functionality, so users outside the Netherlands, or in the NL without a university account, can use the Media Suite with open collections.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/x-omgeving #3](https://github.com/beeldengeluid/x-omgeving/issues/3) via [**ZenHub**](https://www.zenhub.com/)
