### ISSUE TITLE
As a scholar I want to view the EYE Desmet Poster collection in the MS

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#204]
This epic includes stories related to access/viewing the content of EYE Desmet poster collection.

In version 2, the metadata of the posters is available, but the images are viewed/loaded via the EFG portal, ideally, these images are uploaded to a IIIF server and be provided directly via EYE's server.

**Comment by lilimelgar** [comment]
Moved to #293

**Comment by lilimelgar** [comment]
After testing production version July 16 it seems the images are not yet made available in IIIF server.

**Comment by jblom** [comment]
posters are only on efg. I don't remember why they were not available for IIIF. Have to ask EYE again

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-playout-proxy #1](https://github.com/beeldengeluid/labs-playout-proxy/issues/1) via [**ZenHub**](https://www.zenhub.com/)
