### ISSUE TITLE
As a scholar I need to be able to use proper date fields for inspection/analysis of the Eye Desmet collection. 

### ISSUE THREAD

**Issue by wmelder** [CLARIAH/wp5_mediasuite#212]
The raw EYE data for the Desmet collection from the EYE catalogue CSV export contains date information that can't be indexed as date fields in ES because it is carrying 'extra' information (that is only readable and meant for humans).

To fix this (make it readable for the ES date indexer):

- [x] an additional column must be added to the ES index with the proper mapping.
- [x] the human readable data must be preprocessed and only 'cleaned' date information must be indexed.

The 'eye-desmet-films' and 'eye-desmet-affiches' collections contain the following fields that are to be cleaned:

- Releasedatum
- Jaar identificerend
- Copyrightdatum
- Productiejaar
- Releasedatum video (leeg, bevat geen waarden)
- Keuringsdatum
- Releasedatum Nederland (leeg, bevat geen waarden)
- Premièredatum
- Nederlandse premièredatum

The type of class that needs to be created for this is new to the media suite and needs to be reusable or extendable for other collections.

ACCEPTANCE:
- Media Suite user must approve the fix and confirm that it solves the problem.
- code must be tested and merged to the labs-importer master branch.

**Comment by lilimelgar** [comment]
After testing (production version, July 16), still pending:
- [ ] Date fields for the Desmet poster collection are missing

**Comment by wmelder** [comment]
@lilimelgar the dates were fixed some time ago. I should have send you a message probably, but maybe you can check the dates together with the other completeness issue. It should be oke now, but maybe I missed some date formats... If it's ok, you can close the issue.

**Comment by lilimelgar** [comment]
Tested on master, both Desmet film and poster collections date fields are OK now for inspection.
