### ISSUE TITLE
Include version number in home page

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#216]
Add version number with link to Github release note file when ready.

**Comment by avlisodraude** [comment]
@lilimelgar : Version number has been added to the footer along with a link to the Github release notes as in: 
![screen shot 2018-01-04 at 10 00 53](https://user-images.githubusercontent.com/5918438/34556382-52517864-f136-11e7-9347-85cdd318cd6a.png)
