### ISSUE TITLE
End-date boxes overlapping in Comparative search recipe

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#226]
After the implementation of the styling for the Comparative search tool, the date boxes are overlapping the gray areas of the different queries, see below:

![screen shot 2017-12-07 at 10 22 07](https://user-images.githubusercontent.com/8133228/33707731-b60ddb9a-db38-11e7-8bd0-58176f7645ae.png)

**Comment by avlisodraude** [comment]
@liliana: input fields modified to avoid expanding outside parent container. Work can be checked in the branch and will be available in master tomorrow.

**Comment by lilimelgar** [comment]
Fixed and tested in master.
