### ISSUE TITLE
As a scholar, I don't want to get confused about fields names in De Smet collection especially the label "poster" which is not a "poster" but a keyframe"

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#233]
In the Desmet film collection, some of the results bring a thumbnail indicating there is a poster, but when you click on the thumbnail, it does not link to the record of the poster (example screenshot below from: id=FLM43646, eye-desmet-films). In other cases, the record shows an ID with a link to a poster, which opens the search tool with a query for the poster ID, really nice! the first case is a bit strange, the second one is very OK!:

![screen shot 2017-12-14 at 20 59 43](https://user-images.githubusercontent.com/8133228/34012123-d40031ea-e112-11e7-9c01-077ffbbdc374.png)

**Comment by jblom** [comment]
the "poster" in your example is in this case the so-called poster keyframe used for the video. On e.g. YouTube you also have these to illustrate the search results & recommendations. 

In summary the poster image in your example does not refer to the "affiche", but to the "poster frame" that was selected to represent the video file/film

**Comment by lilimelgar** [comment]
I see what you mean :). 

This issue is then just about confusing labelling of the fields, perhaps use "keyframe"  or "video keyframe poster" for the current "poster" to be more precise and to distinguish it from the "affiches":
![screen shot 2018-01-16 at 10 56 43](https://user-images.githubusercontent.com/8133228/34982922-26209d0e-faac-11e7-9d4d-9222f51fe79e.png)

**Comment by roelandordelman** [comment]
I suggest rephrasing the issue into "As a scholar I don't want to get confused about fields names in De Smet collection especially the label "poster" which is not a "poster" but a keyframe". @jblom, is this an easy-to-fix? If not, I suggest icing it.

**Comment by jblom** [comment]
@roelandordelman this is an easy fix. I can just rename the default "poster" to e.g. "video keyframe"

**Comment by jblom** [comment]
I just renamed poster -> keyframe it's only in the master, but will put it in test by the end of the afternoon

**Comment by lilimelgar** [comment]
Tested in Master (updated Jan.24), perfect!
