### ISSUE TITLE
Restaure value list for Y axis in Collection inspector after initial selection

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#239]
Currently, in the Collection Inspector (Inspect tool), if you select a metadata field (value) from the pick list in the Y axis, and try to delete it/go back to the previous list, it stays fixed. One cannot go back to the original list, the only way is to load the collection again. The desired behaviour is that if you press on the arrow you get back the entire list and can select another term.
see problem [here](https://drive.google.com/open?id=1NeVBk13A_AgD4s69zIl8qp2PgR6Hdhyf)

**Comment by avlisodraude** [comment]
@lilimelgar :now once you reset the autosuggest field the graph reset too to reflect correctly the fields selected.

**Comment by lilimelgar** [comment]
Done. tested in production version (v2).
