### ISSUE TITLE
Make available Open Beelden Collections (B&G) as Linked Open Data

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#241]
DESCRIPTION:
These two test collections should be made available both in Elastic Search and LOD as part of the linked data integration in the MS (to test importers and workflow in the entire MS with all tools).
The Open Beelden collections are available in DIVE as LOD.
The collections 'open-beelden-beeldengeluid' en 'open-beelden-eye' zijn beschikbaar in ElasticSearch als RDF.

TODO:

- Install a triple store (e.g. ClioPatria, GraphDB, Jena, ...)

- Download the collections from ES using scroll api and on a designated server (_Lepelaar_ will be primary server, _Zorin_ is now available).

- Load the RDF in a Graph on the triple store.

ACCEPTANCE:

- Check whether SPARQL requests are available.

- Check to what extend identifiers are exchangeable.

- Make a list of issues that prevent interoperabillity.

**Comment by wmelder** [comment]
The collections 'open-beelden-beeldengeluid' en 'open-beelden-eye' zijn beschikbaar in ElasticSearch als RDF. 
TODO: 
- Install a triple store (e.g. ClioPatria, GraphDB, Jena, ...) 
- Download the collections from ES using scroll api and on a designated server (Lepelaar, Zorin).
- Load the RDF in a Graph on the triple store.
ACCEPTANCE:
- Check whether SPARQL request are available

**Comment by c-martinez** [comment]
Script: https://github.com/c-martinez/ld-integration
 - Runs triplestore (virtuoso) on docker container
 - SPARQL endpoint responds to SPARQL queries
 - ID's are same as on ES

**Comment by roelandordelman** [comment]
What is the status of this issue? As it is in Review/QA I assume there is something that needs to be discussed before it can be completed?

In order to have the acceptance criteria more clear, I'd suggest rephrasing the description of this issue into "As a developer, I want to use the Open Images collection in LOD format in order to XYZ"

(apologize if I interfere with discussions but I'm cleaning up the sprint info ;))

**Comment by c-martinez** [comment]
I put it in Review/QA so that it can be tested and marked as complete. I was hoping @wmelder or @jblom might have time at some point.

**Comment by roelandordelman** [comment]
okay, I put it in test and assign to @jblom

**Comment by jblom** [comment]
@roelandordelman @c-martinez @lilimelgar @wmelder so I tested Carlos code, which works swimmingly. So the thing for me to do next is make sure we can have a home for this code. Today I'll be finally freeing up this server, which would be perfect for running multiple Docker containers with triples. 

Together with Carlos we'll be working on:
1) properly connecting the search API to the SPARQL end-points 
2) migrating DIVE data to this new environment (Docker/Virtuoso)
3) rewiring DIVE to work with Elasticsearch for free-text search  + the new triplestore (using the adapted search API: see #1)
4) working on an automated flow for importing all other (JSON-LD) collections into RDF

So these 4 things are at least a GH story each.

**Comment by lilimelgar** [comment]
@jblom Is there a user test to do?

**Comment by jblom** [comment]
@lilimelgar not yet. It's only back-end stuff so far

**Comment by jblom** [comment]
Ok I'm closing this issue, since it's done and the user facing side will be testable after finishing issue #310
