### ISSUE TITLE
As a developer, I need to finalize issues pending from version 1, so I can move on to the development of the new version

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#243]
This epic groups the issues that are required to finalize version 1

**Comment by roelandordelman** [comment]
After sprint one, this epic will be replaced with new 'on topic' epics, e.g., related to CKAN (#88), an epic on Soundbites (theme: data integration), etc. 

@lilimelgar: maybe you some of the issues mentioned have already epics?

**Comment by lilimelgar** [comment]
@roelandordelman Done: I left in this epic only those issues that were clearly urgent fixes of version 2, and moved the others to their theme/epics.

**Comment by lilimelgar** [comment]
Pending issues were moved to their epics.
