### ISSUE TITLE
As a development team supporter, I need to collect user stories showing integration of data (ES and LOD)

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#247]
There are at least three stories now:
1) from Dive, user stores an entity or media object, it goes to common work space
2) from MS tools, resource viewer: user see a button saying "explore this entity" and goes to DIVE
3) from MS tools, resource viewer: user see entities that have been extracted per media object

Collect more of these.

**Comment by lilimelgar** [comment]
@c-martinez, @jblom and @wmelder: I have collected some stories in a report [here](https://docs.google.com/document/d/1iW2DKqmHIl7zT1hcegi8S3mdgo_apHf734OGe4daLEk/edit#). Please let me know if this is useful, any suggestions to improve it are welcome.

**Comment by c-martinez** [comment]
@lilimelgar -- sorry it took me some time to read it. I've added a few comments on the document.

There are one or two of the use cases which are concrete enough to give us some idea of what needs to be implemented, but a lot of them make me wonder: Do we need linked data for this? Or is it just a complex search? Maybe what we are missing also is to have more a more clear idea of when linked data really shines.

**Comment by lilimelgar** [comment]
Thank you @c-martinez for your input. We miss indeed more advanced uses of linked data (do you mean for example using data from Dbpedia or wikidata to create more inferential queries?). Could you please list a couple of examples of the most interesting uses we may not have been aware of? I can use them to continue doing further interviews to refine the use cases. There is also a master student working on a project to link the GTAA thesaurus to Wikidata, more use cases may emerge from this. For the moment, the scope of the document is basic then, more centered on the design of the MS once all data is available as LOD.

**Comment by c-martinez** [comment]
Hi @lilimelgar -- yes, that is more or less what I meant. Unfortunately I don't have any concrete examples which come to mind at the moment. Maybe @biktorrr may have some ideas?

**Comment by lilimelgar** [comment]
@c-martinez @biktorrr Hi Carlos and Victor, are the stories clear/complete for version 3?, can I close this issue? or please let me know what other stories should I add (version 3 of the MS is the priority now).

**Comment by lilimelgar** [comment]
@c-martinez @biktorrr Hi Carlos and Victor, are these stories clear for version 3? shall I close the issue? or do I need to collect more for v3?

**Comment by c-martinez** [comment]
Hi @lilimelgar -- from my side, we could close this issue. It would still be nice to have more concrete examples. @biktorrr -- what do you think?

**Comment by biktorrr** [comment]
Hi Carlos,

which ones do we have now?

best
--victor

**Comment by c-martinez** [comment]
Hi Victor,

Have a look at the `User stories` section of [this document](https://docs.google.com/document/d/1iW2DKqmHIl7zT1hcegi8S3mdgo_apHf734OGe4daLEk/edit#heading=h.pp341oewto5j) but basically user stories boil down to:

 - Linking to ES entity from LD entry
 - Linking to LD entry from ES entity

**Comment by biktorrr** [comment]
Right. Looks good to me!
-victor

**Comment by jblom** [comment]
@lilimelgar @biktorrr @c-martinez closing this issue, since it is not related to development work and could easily be discussed in mail/Slack (cleaning up the myriad of issues)
