### ISSUE TITLE
Investigate feasibility of redirecting user queries to multiple back-ends

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#248]

**Comment by c-martinez** [comment]
This is a feature already requested on grlc, but not yet implemented. See also: https://github.com/CLARIAH/grlc/pull/79

**Comment by roelandordelman** [comment]
@c-martinez / @biktorrr can you reformulate this issue given the above (I assume the user is a developer in this case?). As a developer I want to know / be able to ...

**Comment by c-martinez** [comment]
"As a developer I want to be able to run SPARQL query A on backend X, backend Y or backend Z"

`grlc` feature request (yet to be implemented) considers this use-case specifically:

Query to `http://grlc.io/api/user/repo/query?endpoint=X` will run query on endpoint X, while query to `http://grlc.io/api/user/repo/query?endpoint=Y` will run query on endpoint Y.

**Comment by c-martinez** [comment]
Feature implemented in grlc:
https://github.com/CLARIAH/grlc/issues/76

**Comment by jblom** [comment]
and now also integrated in the search API. Closing this issue
