### ISSUE TITLE
As a system engineer, I need to extend the Search API so it can communicate with the triple store using SPARQL

### ISSUE THREAD

**Issue by jblom** [CLARIAH/wp5_mediasuite#249]

**Comment by jblom** [comment]
@c-martinez I renamed this story (which was about porting the plugin structure to work with ES) so it is about extending the search API with a specific SPARQL (API) end-point/route instead.

I think it is not really necessary for now to port the search API plugin structure to ES, since we will be focussing on rewiring DIVE anyway (I'll just keep the old search API running for that purpose)

**Comment by jblom** [comment]
@c-martinez any update you can give on this story?

**Comment by c-martinez** [comment]
Basic SPARQL functionality ready [here](https://github.com/beeldengeluid/labs-search-api/pull/24). grlc queries not yet fully supported.

**Comment by jblom** [comment]
I've also tested the communication with a SPARQL end-point spun up in a Virtuoso Docker container. It works nicely. Will deploy the search API in the test cluster soon. After that production should follow soon (probably early next week)

**Comment by c-martinez** [comment]
Grlc queries are working -- see [PR](https://github.com/beeldengeluid/labs-search-api/pull/26)
