### ISSUE TITLE
As a scholar I want to add personal collections to the MS, so I can use the tools and available data in combination with my own data

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#252]
Our first focus is on the following (simplified) user story:

As an Oral History scholar, I want to upload my personally collected interviews to the MS. I want to be able to:
- create a collection and provide collection metadata
- provide metadata per uploaded file
- annotate my collection data
- apply an enrichment service on it (speech recognition)
- search my collection (based on manual metadata and enrichments)

**Comment by jblom** [comment]
See #290 I've now deployed this on the test server. For searching your own collection you need to know the collection ID and paste it in the URL of the search page (since I did not implement anything for selecting your own collection)

**Comment by jblom** [comment]
@lilimelgar I'd say test the 290 thing and then close this issue as well. For enriching (personal) collections another issue should be created, since it involves a whole new level of work.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-user-space-api #4](https://github.com/beeldengeluid/labs-user-space-api/issues/4) via [**ZenHub**](https://www.zenhub.com/)
