### ISSUE TITLE
Split documentation page into multiple pages per section

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#253]
Currently, the documentation is all in one page, the request is to split the text into different pages, each page containing a single section of the documentation, and keeping the index in one page.
https://clariah.github.io/mediasuite-info/

**Comment by roelandordelman** [comment]
Looks good! @lilimelgar: can this one be closed?

**Comment by lilimelgar** [comment]
Ok, tested in production version 2.1.
Pending to fix:
-Update links to MS from blog page: https://clariah.github.io/mediasuite-blog/
-Update version number in Documentation pages (from 2.0 to 2.1)
