### ISSUE TITLE
As a developer supported I need to Investigate and provide clear requirements for content words frequency access/visualization

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#255]
There are different alternatives to solve the request of providing word frequencies (word clouds) based on content for different media types. This issue is to investigate alternatives and sketch solutions.
Time frame:
-Liliana investigate alternatives
-Roeland/Liliana discuss alternatives (Jan.16/17)
-Adopted solution goes into sprint planning #2

**Comment by lilimelgar** [comment]
Requirements are clear now, issues are added to the Epic.

**Comment by lilimelgar** [comment]
I reopened this issue since the requirements for the word clouds are not clear yet, there are different processing options, which Liliana will evaluate with scholars during March/April, 2018.

**Comment by jblom** [comment]
@lilimelgar also closing this one since it's no development work
