### ISSUE TITLE
As a requirement analyst, I need to evaluate MS v2 with users, so I can incorporate user feedback into development of version 3 and 4

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#259]
As intermediary between users and developers, I need to evaluate the current release version and align requirements again for version 3.

**Comment by roelandordelman** [comment]
This story is too broad. Can this be made more focussed?

**Comment by lilimelgar** [comment]
This is an Epic. User stories are (would prefer to keep them as ToDos:)

1. Organize talk aloud sessions with volunteer scholars from WP5
2. Organize talk aloud sessions with volunteer pilot scholars
3. Collect all issues and classify: (a) small improvements: add to existing development EPIC/Issue (add in Github), (b) big ideas/suggestions: add to Development challenges and investigate
