### ISSUE TITLE
As a scholar I want (visualisations, word clouds, etc) of my saved query in a research viewer of my query

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#263]
(Describe Epic here)

--
This Epic was previously about the workspace:

This Epic includes all issues related to improving the current version of the Workspace (v2), mainly:  the views of user annotations currently available: Bookmark-centric viewer and Annotation-centric view. See also improvements to "Exports" in Epic #106, which include fixes to the exporting facilities in the workspace.

**Comment by roelandordelman** [comment]
@jblom Can you reformulate this EPIC to make concrete what exactly "improved" means, focussing only on annotation? (with focus on V3 / V4)

**Comment by lilimelgar** [comment]
I closed this Epic since most issues were related to the Workspace (and the Epic title was changed by Roeland to working with Saved queries). So: There is a new Epic with Roeland's title, and the issues that were still open in this Epic and were related to the Workspace were moved to the general improvements Epic #478
