### ISSUE TITLE
As a scholar I want to search the OH collections from Verteld Verleden in the MS

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#266]
This epic had a broader scope: "As an oral historian, I need to access the content of oral history interviews that are provided in the Media Suite, so I can analyze the (visual/audio) content of the interviews and not their metadata only", it includes several stories that aim to facilitate access to the content of the oral history interviews now available in the Media Suite. Content means:
-The audio or video files and/or
-The manual transcripts of those files

Most needed collections (pilot requirements):
-Integrate/make available oral history collections from Verteld Verleden, Erfgoed van de Oorlog, en Getuigen verhalen collections

**Comment by lilimelgar** [comment]
@roelandordelman: please update (or close?) this Epic.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-importer #10](https://github.com/beeldengeluid/labs-importer/issues/10) via [**ZenHub**](https://www.zenhub.com/)
