### ISSUE TITLE
As a scholar, I need to use controlled vocabularies created by others or by myself, so I can annotate (code/classify) my corpus and explain my method more consistently

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#268]
This Epic includes stories that aim to enable users to:
-Use external vocabularies during their coding/classification tasks
-Upgrade their personal or project-based "code books" to vocabularies that can be shared

ToDo (convert into issues if necessary):
-Integration of WW2 thesaurus (NIOD)
-Investigate solution of integration with Onomy.org
-Create hierarchies with the labels assigned to annotated objects/entities

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #39](https://github.com/beeldengeluid/labs-search-api/issues/39) via [**ZenHub**](https://www.zenhub.com/)
