### ISSUE TITLE
As a scholar, I need to add annotations based on tiers, so I can do a proper analysis of audio-visual sources

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#270]
Tiers include two important requirements: (1) that it is possible to created nested segments & create dependencies between segments and (2) that is is possible to name (label) the type (assign a broad category) of segment, (3) that is is possible to create hierarchies of the types of segments (labels). Requirements 2 and 3 are possible at this moment with the "classification" functionality of the annotation 2, but only for a single row of segments (only one layer of segmentation)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-annotation-api #4](https://github.com/beeldengeluid/labs-annotation-api/issues/4) via [**ZenHub**](https://www.zenhub.com/)
