### ISSUE TITLE
As a scholar, I want to collaborate with other users in (projects in) the workspace

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#271]
This requirement will be part of the CLARIAH wide Workspace work taken up in a separate project. I expect there may be dependencies on the user authentication/management level. Contents of this epic needs to be formulated in more detail in a "plan" (or as part of another plan)

**Comment by roelandordelman** [comment]
As this epic is still "void" I move it to the 'new issues'

**Comment by lilimelgar** [comment]
@roelandordelman Requirements will be added (moved it to Icebox until ready)
