### ISSUE TITLE
As a scholar, I need to have access to EYE's documentary & experimental film collections, so I can have a more complete corpus of Dutch productions

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#274]
This Epic includes user stories aiming to provide access to Dutch documentaries and experimental films from the EYE collection. Related to Epics and user stories about EYE data integration and playout: #203, #191, #204. 

EYE's documentary film collections is of high value for film/media scholars, and potentially historians, who would benefit from having access to these collections simultaneously with the collection of documentaries from B&G. They need both the metadata and playout (and use the annotation tools of the MS with both collections).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-importer #3](https://github.com/beeldengeluid/labs-importer/issues/3) via [**ZenHub**](https://www.zenhub.com/)
