### ISSUE TITLE
As a developer, I would like to fully integrate the ANP radio bulletins into the Media Suite and align them to radio programs, so this open collection can be used and linked

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#275]
This collection was available in version 1 but no longer in version 2:
http://mediasuitedata.clariah.nl/dataset/kb-anp-radiobulletins

This epic includes issues to make it available again, and other issues investigating the aligment of the bulletins with the corresponding audio records. The dataset is available as LOD (enriched) via DIVE, also include user stories related to linked data using this collection.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-importer #2](https://github.com/beeldengeluid/labs-importer/issues/2) via [**ZenHub**](https://www.zenhub.com/)
