### ISSUE TITLE
As a service provider, I need to add a "terms of service"/policy document to the Media Suite

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#277]
Add "terms of service" document. Users should agree explicitly on two things:
-Fairness of use of the data
-Being "tracked" in analytics system for improvement purposes
Explain conditions of use of the content and metadata offered by the Media Suite.

**Comment by lilimelgar** [comment]
Moved as a ToDo for documentation.

**Comment by lilimelgar** [comment]
@avlisodraude Can you please add a link in the footer of the MS, label it: "Terms of service". The link does not work yet, the document is being prepared, but it's good to add it to the footer now.

**Comment by lilimelgar** [comment]
This is done for V3, added link to documentation page in the footer. More content may be added to docs, not to MS.

**Comment by lilimelgar** [comment]
@avlisodraude: The link to the terms of service is not there in the production version.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #153](https://github.com/beeldengeluid/labo-components/issues/153) via [**ZenHub**](https://www.zenhub.com/)
