### ISSUE TITLE
Add labels to timeline chart used by the Comparative search recipe

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#28]
Latest request: this is the same as issue #39 (adding labels to the X and Y axes).

--
OLD:
In the time line chart that is used by the Comparative search recipe. (See also issue #79). Please fix:

(1) Add X axis label (i.e., this label is added automatically picking up the name of the field selected in the time selector, e.g., "datestamp")

(2) Add Y axis label (i.e., number of results)

(3) Add key or legend

(4) Add Chart title (generated automatically combining query terms)

Related to solved issue #80

**Comment by lilimelgar** [comment]
Comment from April 4 meeting: The graph of date of publication seems very arbitrary (2005.2)

**Comment by lilimelgar** [comment]
Related to #91

**Comment by avlisodraude** [comment]
@lilimelgar This ticket might require some clarification:
Not sure what: "Add key or legend" means in this context ?

**Comment by lilimelgar** [comment]
Thanks. Please take a look to t[his document](https://docs.google.com/document/d/1SGWMcO5w6UsAENlaBlaoVVQCB2n5TtBS8PBfdy41FSg/edit#) where the parts of the graphic are named. The key/legend is the text that is added to indicate what colors or shapes have been used in the graphic for which data. Please see also issue #79

**Comment by lilimelgar** [comment]
Merged with #39
