### ISSUE TITLE
As a developer, I need to check possible issue with indexing B&G keyword fields

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#281]
There seems to be an issue in the indexing of genres in B&G collection. Search:
—Trump
—All fields
—Dates (sortdate in publications) range 01-01-2016 to 01/01/2018
—I get 4580 results, if I use the facet Genre (field Program: Genre (in genres)*, I only get one genre (period-overzicht) with one occurrence, but if I click on random results, I see they have other genres in the mentioned field, which don’t seem to be indexed

![screen shot 2018-01-22 at 15 01 57](https://user-images.githubusercontent.com/8133228/35224432-440e7c0e-ff85-11e7-9344-15ef5a1d0561.png)

**Comment by mwigham** [comment]
Can you check if the other genres you see are indeed in the program genre field, or are they perhaps in the series genre field?

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #54](https://github.com/beeldengeluid/labs-search-api/issues/54) via [**ZenHub**](https://www.zenhub.com/)
