### ISSUE TITLE
As a user, I would like to see what is the name/label of the fields used for facets in the facet builder, so I can trace back which metadata is being used for the aggregations

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#282]
This is similar to issue #126  with dates, obtaining the label of the field used for the facets in the facet builder. See [screencast](https://drive.google.com/open?id=1Lf7gCXIMel4gSzdNcfsNO8N0jfB1fD0i).

**Comment by avlisodraude** [comment]
@jblom : changes commited to branch https://github.com/beeldengeluid/labo-components/pull/56/commits/f044f206dbe1153113d196a58edefe1b91a0d30f

**Comment by lilimelgar** [comment]
Done :) tested in Test version (June 12)
