### ISSUE TITLE
As a scholar, I need to have access to the broadcasting guides (Omroepgidsen), so I can do have contextual data and a more complete corpus in my research

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#284]
Roeland description (moved from #273): This Epic is done from the technical side, but requires work on other types of restrictions. The collection needs also evaluation once is available.
To be done: integrate user stories.

--
Linking broadcast items to the Program guides is essential to facilitate media research.
This description was given by one scholar about the importance of creating this link:

"The programme guides offer the possibility to contextualise audiovisual collections of broadcasting archives. The program guides are important for media historical research into broadcasting history as they represent “sources” containing the textual and contextual information related to items in audiovisual collections. The contextual information contained in programme guides which are of particular importance are:
- day-by-day broadcasting schedules
- Interviews with programme makers
- Articles containing reception info or reviews of programmes
- Articles containing production details or style/genre classifications
The manner in which the programme guides can be used in the MS depend greatly on the research question posed by the researcher. In general, however, the inclusion of the programme guides in the MS enables to create “interrelated,” researcher-driven metadata, in which: items in AV-collections (EYE. NISV) can be linked to items in textual collections (Omroepgidsen) in order to ascertain information not provided in metadata of the former. For example:
- When and at what time was it broadcasted? 
- Which programs preceded or succeeded it?
- Was the creator/producer interviewed in the guide? 
- Which contextual information is given about its production?
- How was the program (or aspects of it) evaluated? 
By integrating the program guides into the MS, the above questions can be answered and linked to each other in order to create a more complete, interlinked set of research data. " (Tom Slootweg, personal communication, 22 January, 2018).

We have to evaluate whether we want to try an automatic way of doing this linking. Themis had started this already (Liliana has some of the files), or if we have the linking functionality of the annotation component ready, we could also facilitate manual linking (which applies to transcripts for OH audio/video, and to letters -Mimehist- to video fragments). Manual linking could be done for testing: connected to Epic #23

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-importer #4](https://github.com/beeldengeluid/labs-importer/issues/4) via [**ZenHub**](https://www.zenhub.com/)
