### ISSUE TITLE
As a user, I would like to see a clear link to the EYE's catalog, so I can access the original record

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#287]
In the EYE's Desmet collections, there is a generic message in the Resource viewer (fix from issue #54), the message is not precise enough, please change:

"View in Eye's catalog: Not direct link, use the "ID" to search in eyefilm.nl" to:

"View in Eye's catalog: Not direct link, use the "ID" to search in the EYE collectie catalogus: https://www.eyefilm.nl/eye-catalogus-zoek-in-de-collectie"

**Comment by jblom** [comment]
I fixed this locally, whenever you're ready to test, I can send you the new mapping files that fixed this

**Comment by lilimelgar** [comment]
Done!
