### ISSUE TITLE
As a scholar, I want my added files to get processed by the speech recognition service

### ISSUE THREAD

**Issue by roelandordelman** [CLARIAH/wp5_mediasuite#291]
The private files provided by a user (and downloaded from dropbox) are put on the watch folder of the NISV local ASR service. There the file will be picked up by the ASR. The result will be put back in an "out" folder. We don't need to do a check for media as the ASR does this (maybe we do this later for feedback purposes). 

Tasks
- [ ] make a CLARIAH user account on the ASR service (for the CLARIAH watch folder) - Willem
- [ ] create a mechanism to push downloaded files to dropbox and receive/index result transcripts - Johannes
- [ ] check ASR provenance (Roeland)

**Comment by roelandordelman** [comment]
@jwassenaarbg       database integratie

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/asr-av-archive #5](https://github.com/beeldengeluid/asr-av-archive/issues/5) via [**ZenHub**](https://www.zenhub.com/)
