### ISSUE TITLE
As a scholar, I want to search speech transcripts of (OH) collections in the Media Suite

### ISSUE THREAD

**Issue by roelandordelman** [CLARIAH/wp5_mediasuite#296]
This EPIC creates the first version of a Media Suite interface on audio only collections, such as required by Oral Historians or scholars interested in audio only. The focus here is on using time-based verbatim metadata transcriptions (e.g., coming from ASR) in search and slightly different annotation options. Also, the alignment of verbatim (but not time-aligned) transcripts play a role here.

For V3 we build a "single-search for audio" instance (e.g., http://mediasuite.clariah.nl/tool/single-search-audio) that behaves exactly like the current single search with respect to selecting data, however, the collection selector allows the selection of OH or Radio (for now) data only. 

The first stories for this EPIC are:
- creating an index for the Radio ASR currently running at SURF (100K radio items)
- creating a baseline search recipe
- creating a "resource viewer" specialized for audio

**Comment by lilimelgar** [comment]
I have a question/suggestion here:
from a user perspective, in my humble opinion, oral historians (and other scholars) may not look for this specific combination from a scholarly perspective, except if their research questions are "forced" to be shaped by the actual supply of these enrichments that are offered to audio content. I would see this Epic, from user's eyes, like this:

"as a user, I would like to be able to search the content of audio materials by using their transcripts, no matter where the audio materials are in a given collection"
That is, the scholars would like to be able to select collections by type as we have them now (OH interviews, newspapers, television, radio, etc.), and within those collections be able to search or browse the audio content by using the textual transcripts that are available (now for audio content).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/asr-av-archive #4](https://github.com/beeldengeluid/asr-av-archive/issues/4) via [**ZenHub**](https://www.zenhub.com/)
