### ISSUE TITLE
As a user, I want a recipe for "audio search"

### ISSUE THREAD

**Issue by roelandordelman** [CLARIAH/wp5_mediasuite#298]
This story creates the placeholder for the OH / Radio / audio search environment described in EPIC #296

The audio search recipe is a copy of the current single-search recipe, however, it only allows the user to search in audio collections (typically OH or Radio currently).

Acceptance criteria for this version:
1. single-search-audio recipe
2. collection selection: any audio collection with ASR
3. search  any audio collection with ASR

**Comment by jblom** [comment]
putting this in the icebox for now, since I think we don't need a separate recipe for V4 for now. It would make more sense imho to work on a really dedicated audio recipe/page for B&G internal user
