### ISSUE TITLE
As a user, I want to browse a speech transcript in the resource viewer of the audio search recipe

### ISSUE THREAD

**Issue by roelandordelman** [CLARIAH/wp5_mediasuite#299]
Baseline of this story is that the user has an audio player and a transcript viewer so that the user:
 
(i) can read along with the speech transcript while listening to the audio.
(ii) can browse through the audio by clicking on segments in the transcript 

Additional features (not for this story, but good to know):
- user can correct errors in the transcript
- user can edit segmentation (e.g., grouping, assigning speaker label)
- user can ask for enrichment of the transcript (e.g., named entity detection)
- etc.

**Comment by jblom** [comment]
@avlisodraude to work on this story you basically need to:

1) create a new version of the ItemDetailsRecipe, one that focusses on playing out audio/video and focusses on functionalities related to the audio transcript
2) start working with a dummy transcript (in JSON) so you can start creating the necessary UI elements/controls
3) @wmelder and myself will take care of providing you with the data/API for the real transcripts

A general suggestion: look at themindoftheuniverse.org and discuss the desired functionalities with @roelandordelman

**Comment by wmelder** [comment]
I'll send Eduardo the player that I wrote..

**Comment by jblom** [comment]
Now I completed the chain of searching the ASR and being able to load the transcript in the resource viewer. @avlisodraude ping me whenever you're ready for this. I want to do a couple of cosmetic changes before I push it to the master (or deploy it to the test server for that matter)

**Comment by jblom** [comment]
Separate from actually connecting ASR results with the transcribed resources (back-end), this works now (in the UI) for all AV (except for B&G audio, which should be fixed somewhere end of this month).

**Comment by roelandordelman** [comment]
@jblom will the fix for BG audio happen automatically or is there an action required?

**Comment by jblom** [comment]
@roelandordelman I'm pretty sure the end-point will change so a mapping file in the media suite code has to be changed. I'll add this to my doc as well
