### ISSUE TITLE
Hide "Document type" menu in Collection inspector 

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#3]
Select document type: delete option from interface.

![screen shot 2017-08-31 at 07 52 18](https://user-images.githubusercontent.com/8133228/29908385-5af36568-8e21-11e7-8ea8-16744905143b.png)

**Comment by lilimelgar** [comment]
Further user evaluation shows the same need.

**Comment by avlisodraude** [comment]
Done along with #129 for making search icon clickable and search within the collection. 
Already in branch "task/#129-make-search-icon-clickable" waiting to be merged into Master branch

**Comment by lilimelgar** [comment]
OK :)
