### ISSUE TITLE
As a developer I need to handle ES server error that causes index creation to fail

### ISSUE THREAD

**Issue by wmelder** [CLARIAH/wp5_mediasuite#301]
<class 'elasticsearch.exceptions.TransportError'> TransportError(503, {u'root_cause': [{u'reason': u'failed to process cluster event (create-ind
ex [nisv-catalogue-aggr-18-032], cause [api]) within 30s', u'type': u'process_cluster_event_timeout_exception'}], u'type': u'process_cluster_eve
nt_timeout_exception', u'reason': u'failed to process cluster event (create-index [nisv-catalogue-aggr-18-032], cause [api]) within 30s'})
503 {u'root_cause': [{u'reason': u'failed to process cluster event (create-index [nisv-catalogue-aggr-18-032], cause [api]) within 30s', u'type'
: u'process_cluster_event_timeout_exception'}], u'type': u'process_cluster_event_timeout_exception', u'reason': u'failed to process cluster even
t (create-index [nisv-catalogue-aggr-18-032], cause [api]) within 30s'}

**Comment by wmelder** [comment]
code is now checking explicitly for 503 exception and raises the error
because the type ES transport error with code 400 must be ignored, it went wrong...

**Comment by wmelder** [comment]
- Branch from master (issue#301 in name branch)
-- Note: index creation 3 shards, no replicas
- Create a test user on (application server) xeniaonatopp.beeldengeluid.nl
- Use test server for data imports (deves2001.beeldengeluid.nl)
- merge after test

**Comment by jblom** [comment]
@wmelder this one should be picked up after we can start harvesting daily again

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-importer #7](https://github.com/beeldengeluid/labs-importer/issues/7) via [**ZenHub**](https://www.zenhub.com/)
