### ISSUE TITLE
As a user, I would like to find clear metadata about the media type of the KB newspaper collection (and other collections)

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#303]
In the result list of the KB newspaper collection, there are two icons indicating media type: image and unknown:
![screen shot 2018-02-05 at 11 18 23](https://user-images.githubusercontent.com/8133228/35799528-4f50b938-0a66-11e8-9f90-ec62a0bd7a4e.png)
This may be a bit confusing for the users.
Since KB newspapers are both image and text, those two icons could be displayed, or choose "text" since newspapers are mostly textual (from a content perspective, not format-based).

Note: most likely is this due to the fact that the KB newspaper collection indexing is still in progress?

**Comment by lilimelgar** [comment]
@jwassenaarbg : after testing on production version (July 16), I see that the icon now is a question mark (non-detected media type). Please check if we should leave this icon, or if this will change, then I can document it.

**Comment by jwassenaarbg** [comment]
@lilimelgar Well, technically it is true, since there is no media, it doesn't have a media-type either. We just show links. I will see if we can use another icon for this collection.

**Comment by jwassenaarbg** [comment]
@lilimelgar Fixed this probably, but need a test with KB data which is not available in the test version yet. I tested it on DANS (which for me showed a video icon for all items even the restricted ones). Dans also shows the new icon now for results that don't have playout. The changes are pending review from Jaap.

This is the icon I used: https://fontawesome.com/v4.7.0/icon/file-text-o

**Comment by jwassenaarbg** [comment]
![screen shot 2018-07-17 at 13 46 31](https://user-images.githubusercontent.com/29273305/42815518-e34e3bb6-89c7-11e8-8c36-8f129d667328.png)

@lilimelgar

**Comment by lilimelgar** [comment]
@jwassenaarbg: I will wait to test in KB later. 
In the DANS screenshot you added, I see a textual icon in the first result: does it mean that the media type is a text (probably a transcript?). If that icon indicates that there is no playout, it should be changed, since the convention used in the rest of the collections is a closed eye:

![screen shot 2018-07-18 at 11 57 12](https://user-images.githubusercontent.com/8133228/42874563-c285f12a-8a81-11e8-83a4-0f2e1213e348.png)

**Comment by jwassenaarbg** [comment]
Oke, then I understood your request incorrectly. I have reverted changes I made. When there is no media, just metadata, there will not be any icon anymore, just the closed eye indicating no playout of any media available. For the KB the icon is therefore also removed, as there is no playout of media, just metadata and a link only. If you want we can find an icon for linked media, then a link icon of some sort could be displayed next to the eye.

**Comment by jblom** [comment]
I removed the unknown media type (question mark icon), since I also think that it can be confusing

All KB items show the text icon (copied this code from @jwassenaarbg ). 

When configuring the media types per collection, now I view the media type/icon from a scholarly perspective: e.g. KB shows a text icon, even though you can see it as an image. Still not sure though if this is the best approach or the icon should reflect the viewer/browser media format

**Comment by lilimelgar** [comment]
@jblom: "Still not sure though if this is the best approach or the icon should reflect the viewer/browser media format." 

How others have solved this:
-Internet archive: the media type of the newspapers is text
-Library of Congress: they assign three types to newspapers:
![screen shot 2018-08-21 at 12 08 53](https://user-images.githubusercontent.com/8133228/44395915-a2560500-a53b-11e8-8236-d51652c0ba5a.png)
-Schema.org: indicates it is a text: https://bib.schema.org/Newspaper

It seems that it makes more sense to go for the user perspective here, and keep newspapers as text. 

Another alternative is to add two types, we could then always assign the viewer/browser format automatically recognized first, and then add the default user type per collection as a second value. Thus, image/text (as two icons, or as a combined icon). This would be also the case of the Desmet paper collection -now shows items as images-.

**Comment by lilimelgar** [comment]
@jblom  Tested in test version. Some pending issues per collection:

-[ ] Beeld en Geluid AV: Some records don't have automatically detected media type. Is this because they are not digitized? (e.g., ID: 4907842@program).
-[ ] Desmet paper collection: if we follow same idea as with the KB, it should be mostly a text icon
-[ ] Oral history collection: @jwassenaarbg  Please check the issue of all collections having video as media type, it should be detected automatically (some are audio/sound interviews).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #181](https://github.com/beeldengeluid/labo-components/issues/181) via [**ZenHub**](https://www.zenhub.com/)
