### ISSUE TITLE
As a user, I may get confused if I see the same icon for two different functions in the result list

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#304]
In the result list, suggested to change the icon from an open eye to another icon (for instance something like a play button?), this is because there is another "eye" icon to view the metadata, same icon for two different functions may be a bit confusing. Another option is to change the other Eye icon for the metadata view on the left into a little "metadata card" or something like that (magnifier glass icon should be reserved for the Inspecting functions). 
![screen shot 2018-02-05 at 11 40 44](https://user-images.githubusercontent.com/8133228/35801389-7e50fab2-0a6c-11e8-8112-a29353195ce5.png)

**Comment by jblom** [comment]
(copied this reaction from the closed issue) On the master I changed the quick-view eye button to a sheet-of-paper-with-text on it. Not sure if that is the best one, but at least it allows for keeping the open & closed eye for conveying the accessibility.

**Comment by jblom** [comment]
@lilimelgar could you test & close this one too? (deployed on test/master)

**Comment by lilimelgar** [comment]
Tested in Master version. Done! cool :)
