### ISSUE TITLE
As a DIVE engineer I need access to the new search API (that can communicate with the MS triple store)

### ISSUE THREAD

**Issue by jblom** [CLARIAH/wp5_mediasuite#308]

**Comment by jblom** [comment]
@c-martinez I deployed the latest version of the search API (with grlc / SPARQL support) in the test environment. After a bit more testing I hope to deploy one accessible for DIVE as well.

**Comment by c-martinez** [comment]
We might need to wait for [this PR](https://github.com/CLARIAH/grlc/pull/95) on `grlc` to be merged.

**Comment by jblom** [comment]
@c-martinez could you please test if the production version of the search API is accessible for you? (and if grlc + sparql works from there) if yes we can close this one

**Comment by c-martinez** [comment]
Seems to work fine.
