### ISSUE TITLE
As a Manager I want to have statistics on the traffic on the mediasuite

### ISSUE THREAD

**Issue by roelandordelman** [CLARIAH/wp5_mediasuite#312]
Make sure this code is on every page of your website. We recommend to paste it immediately before the closing </head> tag.

<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//clariah-mediasuite.innocraft.cloud/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

**Comment by roelandordelman** [comment]
zie code in email

**Comment by jblom** [comment]
@roelandordelman so this one should be done now right? Please close if so

**Comment by roelandordelman** [comment]
It seems to work nicely. I added Julia, Johan, Jaap, and Phuocie (financial) as users. Currently still free trial. Next week basic account. Closing.
