### ISSUE TITLE
As a scholar, I would like to have a pie chart showing completeness/incompleteness of a field in the Collection Inspector

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#316]
Currently, the Inspector tool displays the completeness/incompleteness (missing/complete) of the analysis field along a time line (for a chosen "date field"), this request consist on adding the option to visualize completness/incompletness via a pie chart  for the entire collection (not using the date field as input). 
Then the inspector will include two types of visualizations: time line chart (done) j+ pie chart (to be done).

**Comment by avlisodraude** [comment]
Update, these are the last ToDos:

- [ ] Delete boxes to send collection to "recipe"
- [ ] Move the graph box up, place it just bellow collection and field selectors
- [ ] Move the sub-component "field analysis stats" under the graph
- [ ] Add pie charts next to the line chart, one pie chart is for "date field" and the other one is for "analysis field"

**Comment by lilimelgar** [comment]
This issue is updated by issue #426
