### ISSUE TITLE
Publicly accessible triples store 

### ISSUE THREAD

**Issue by biktorrr** [CLARIAH/wp5_mediasuite#328]
As a developer and advanced media scholar, I want to access the DIVE+ / exploratory search triple stores web UI in such a way that I can inspect the data and do (interactive) SPARQL queries. For this, we would beed to replicate the old situation (data.dive.beeldengeluid.nl is currently a proxy for a Cliopatria triple store's internal port). In the new situation: divedata.clariah.nl could point to the new virtuoso triple store running in the docker

**Comment by jblom** [comment]
Currently SPARQL queries can be done only via the search API, but I agree it's important to also have the Virtuoso UI available. For this we need to publish these on a domain per instance (of Virtuoso)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #48](https://github.com/beeldengeluid/labs-search-api/issues/48) via [**ZenHub**](https://www.zenhub.com/)
