### ISSUE TITLE
As a developer I need to deploy an up-to-date version of OpenConext, so it's possible to continue work on the CLARIAH auth-related requirements

### ISSUE THREAD

**Issue by blokjonathan** [CLARIAH/wp5_mediasuite#338]
**Description**
The ansible scripts voor deploying and provisioning the new OpenConext machine need to be configured to point to the correct address and domain. Once this is done, the Ansible playbook need to be run and possibly debugged. 

**Approach**
Read through documentation and follow steps. Fork the OpenConext-deployment repository in order to save the configuration.

**Acceptance Criteria**
There is a machine in our network which has the web applications running required by OpenConext.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/x-omgeving #2](https://github.com/beeldengeluid/x-omgeving/issues/2) via [**ZenHub**](https://www.zenhub.com/)
