### ISSUE TITLE
Recreate SP to IdP connections from mrbig on lechiffre

### ISSUE THREAD

**Issue by blokjonathan** [CLARIAH/wp5_mediasuite#339]
**Description**
Currently, there are connections configured between SPs and IdPs in the OpenConext environment on mrbig. These need to be recreated on the newly set up OpenConext environment on lechiffre using the new OpenConext components.

**Approach**
A new management interface is available in the latest version of OpenConext can be used to recreate all the connections and rules.

**Acceptance Criteria**
All connections on the old environment are available on the new environment. There is documentation on how this is done.

**Comment by jblom** [comment]
@blokjonathan you are working on this one right? I put it in progress for you, since there was nothing in your sprint.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/x-omgeving #4](https://github.com/beeldengeluid/x-omgeving/issues/4) via [**ZenHub**](https://www.zenhub.com/)
