### ISSUE TITLE
As a user I would like to see "highlighted" the individual words from my Boolean query in the search results

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#346]
The search term is highlighted when it is only one, not the individual words of the boolean query.

Acceptance criteria:
- when searching for e.g. "amsterdam arena" AND "de kuip", both "amsterdam arena" and "de kuip" should be highlighted in the search results.
- when searching for e.g. amsterdam bloemenmarkt AND rotterdam bloemencorso all individual words should be highlighted as well as the phrases on each side of the boolean expression. This means the following should be highlighted (if present): "amsterdam", "bloemenmarkt", "amsterdam bloemenmarkt", "rotterdam", "bloemencorso" and finally "rotterdam bloemencorso"

**Comment by lilimelgar** [comment]
The search term is highlighted when it is only one, not the individual words of the boolean query (tested in master June 11)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #170](https://github.com/beeldengeluid/labo-components/issues/170) via [**ZenHub**](https://www.zenhub.com/)
