### ISSUE TITLE
As a developer I need to design the architecture for securely connecting a Jupyter notebook with the x-omgeving, so it's not possible for notebook users to mess up the infrastructure

### ISSUE THREAD

**Issue by blokjonathan** [CLARIAH/wp5_mediasuite#347]
**Description**
Because we want to use Jupyter notebooks in combination with the Mediasuite Workspace, we need to know a bit about how they are deployed and how it is possible to secure the connection to them. Additionally, we need to make sure our datasets remain secure. 

**Approach** 
It might be possible to deploy a Jupyter service locally for testing.

**Acceptance criteria**
The fundamentals of deploying a Jupyter environment are understood, and a deployment plan is written. We have a clear idea on how we can securely use Jupyter notebooks.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/x-omgeving #1](https://github.com/beeldengeluid/x-omgeving/issues/1) via [**ZenHub**](https://www.zenhub.com/)
