### ISSUE TITLE
As a developer I need to check why the Search tool crashes when adding one specific facet in the B&G collection

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#348]
In the Search tool, B&G collection, add new facet : when user adds the first metadata field 
program => archivestatus (in: carriers)* 
the system crashes.
See screencast [here](https://drive.google.com/open?id=1QZ-AJ6R2cCBUEdcja97zE4iq3n8S1FGf).
This does not happen with other facets, even if the field is empty.

**Comment by jblom** [comment]
@lilimelgar lol @avlisodraude just mentioned this to me this morning and I fixed it already in the master :)))

**Comment by lilimelgar** [comment]
Great! fixed (tested in master) :)
