### ISSUE TITLE
As a developer, I need to check what the problem is when replaying saved queries with the oral history aggregated collection

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#349]
Saving queries works with most collections, but with the OH collection it does not work in some cases (not clear when it happens). 
See [screencast](https://drive.google.com/open?id=1wZZVIPLuc0x7gR7wXAZsj-mmwAnpJ_P9).

(this is the URL of one of the tests that did not work: http://0.0.0.0:5304/tool/single-search?fr=0&sz=20&cids=dans-oral-history&sl=dans-oral-history&st=oorlog%20AND%20meer&fc=descriptions&sf=@graph.dcterms:format.keyword|mixed%20material,@graph.dcterms:isPartOf.keyword|Veteranen%20Instituut,%20IPNV&s=_score__desc)

**Comment by jwassenaarbg** [comment]
One thing I found is that the facet contains a "/" sign. It might go wrong on that one.

**Comment by lilimelgar** [comment]
@jwassenaarbg I tested again, July 16 production version, and this happened again. The problem seems to occur when adding new facets, but not always... see [here](https://drive.google.com/open?id=1wZZVIPLuc0x7gR7wXAZsj-mmwAnpJ_P9).

**Comment by jwassenaarbg** [comment]
@lilimelgar The pull request for the fix I made is to be reviewed by @jblom first before you can test it. I will let you know when we can test it further.

**Comment by lilimelgar** [comment]
Ok! will wait to test this one later.

**Comment by jblom** [comment]
merged this in master, without testing yet. Should be ok though

**Comment by lilimelgar** [comment]
Tested on master (August 15). The queries are stored with all parameters and replay correctly. The only small issue is that sometimes the previous replayed query stays in cached until a hard refresh is done.

**Comment by jblom** [comment]
yes the caching needs to be checked a bit more. Wrote this down

**Comment by jblom** [comment]
@lilimelgar I don't see any problems anymore. Could you test this?

**Comment by lilimelgar** [comment]
Tested on Test version, alles OK!
