### ISSUE TITLE
As a user, I would like to filter my results based on the media type and access options

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#352]
Currently, in the Search tool(s), the result list displays two icons:
-A media type icon (same as issue #260) 
-An eye (open or closed) indicating if the item can be viewed/played

As a user, I would like to be able to find an option to select those items in the result list that are of a given media type (mage, audio, video, text), and a tick box to select those that are only playable/viewable or not.

**Comment by lilimelgar** [comment]
@jblom: You mentioned that the ideal solution to this is that this information is added to the metadata by the content provider. I moved this to the Icebox to wait until we can discuss a proper way to do it.

**Comment by jblom** [comment]
for this to work, the information needs to be added to the index. I'm moving this to CLARIAH+ for now, since it could entail quite the work to the import pipeline

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #40](https://github.com/beeldengeluid/labs-search-api/issues/40) via [**ZenHub**](https://www.zenhub.com/)
