### ISSUE TITLE
As a user I would like to be able to create a new user project from the search tool(s)

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#353]
Currently, a user has to create a user project in the Workspace first in order to be able to see it in the drop-down list of user projects in the search tools. Ideally, a user could find a button to create a new user project in the search tool when s(he) discovers s(he) has to create a new project. [See screencast](https://drive.google.com/open?id=1E7tXt8BcIHCk5_BNNnn46EqOy9CfZQh5).

**Comment by jblom** [comment]
@lilimelgar this was implemented by @avlisodraude and can be tested

**Comment by lilimelgar** [comment]
Yes, tested in master branch, Single and Comparative search with different collections, all good!
