### ISSUE TITLE
As a developer, I need to fix issue with resizing screen of search tool

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#356]
In the Search tool, when the users compress the window, the buttons for ranking/ordering search results get out of place. See [screencast](https://drive.google.com/open?id=1sCl5nbnJ_JC1icoJb5MjSwSZBQYo5O9c).

**Comment by lilimelgar** [comment]
Tested in master (May 16), did not see it solved. @avlisodraude: do I have to check in another branch?

**Comment by avlisodraude** [comment]
@lilimelgar @jblom I'm closing this issue since it's been fixed already and it can be tested in either master branch or test version http://mediasuite-test.rdlabs.beeldengeluid.nl/.
