### ISSUE TITLE
Replace Floating info message in home page

### ISSUE THREAD

**Issue by avlisodraude** [CLARIAH/wp5_mediasuite#363]
To allow the inclusion of relevant information regarding the Clariah project the modal appearing in the header banner should be replace for a slider.
From
![Screen Shot 2018-05-02 at 17.10.42.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/6a024ba4-7dcc-4f95-8eff-da766b10a097)

TO:
![Screen Shot 2018-05-02 at 17.11.36.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/f82deb8d-ea5a-474f-82fc-c5bb1b4ff2db)

**Comment by lilimelgar** [comment]
Done!
