### ISSUE TITLE
As a developer, I want the GTAA thesaurus to contain checked, consistent terms, to improve search results

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#367]
Deliverable: Support to IM in improving GTAA thesaurus.  Acceptance criteria, media manager is satisfied with support

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #58](https://github.com/beeldengeluid/labs-search-api/issues/58) via [**ZenHub**](https://www.zenhub.com/)
