### ISSUE TITLE
Weeknummer / Niet van toepassing in resultatenlijst NISV cat search

### ISSUE THREAD

**Issue by roelandordelman** [CLARIAH/wp5_mediasuite#37]
Waarschijnlijk een veld (titel) leeg in de metadata? Dit komt veel voor dus wellicht op te lossen?

![image](https://cloud.githubusercontent.com/assets/18610579/23220095/232e3dd2-f921-11e6-9a0e-cd3397dd9c8d.png)

**Comment by jblom** [comment]
Dit heeft te maken met het highlighten van de tekst waar het resultaat in gevonden is. De (...) suggereert dat er nog meer text volgt. In het geval van MotU is dit logisch bij teksten van transcripten (bij segment hits), maar voor andere collecties niet altijd. Dit moet ik inderdaad nog eens nalopen.

't staat nu geregistreerd, da's fijn. Dank

**Comment by lilimelgar** [comment]
May be related to #93?

**Comment by lilimelgar** [comment]
Same as #47, works better now (version 2).
