### ISSUE TITLE
As a Media Manager, I want statistics and visualisations that give insight into how the non-compliant terms are distributed over the archive

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#372]
This allows the MM to define strategies for matching the non-compliant terms, and to determine priorities (e.g. more frequently used terms may get priority, or those that are used more broadly in the archive, as opposed to for a very specific segment)

Deliveralbe - software (probably a Jupyter notebook)  that generateds informative statistics and visualisations of the distribution of the non-compliant terms.  acceptance criteria: media manager finds the statistics/visualisations informative for deciding how to handle non-compliant terms.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #57](https://github.com/beeldengeluid/labs-search-api/issues/57) via [**ZenHub**](https://www.zenhub.com/)
