### ISSUE TITLE
As a developer, I need to be familiar with the use of Jupyter notebooks to create visualisations

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#373]

**Comment by mwigham** [comment]
Tried out plotly and d3 visualisations in Jupyter, using the number of terms in each 'as' of the GTAA as the data.  This works well.

![gtaa pie](https://user-images.githubusercontent.com/38520885/39923173-d31db246-5522-11e8-9b81-919cb3fe4e8f.PNG)
![gtaa bubble](https://user-images.githubusercontent.com/38520885/39923174-d3365698-5522-11e8-829f-ce8179a2f603.PNG)

**Comment by mwigham** [comment]
It may well be unusual - I'm so new to Python that I wouldn't know!  I just
know that d3 offers a very wide range of possible visualisations (take a
look here <https://github.com/d3/d3/wiki/Gallery>), and when I googled d3
and jupyter, it turned out to be possible to combine the two.  Most of the
visualisations I did using plotly, though, and I'm definitely for using
python libraries wherever possible, as the javascript can be a right pain
to get working.  I'm also going to look more into other types of
visualisation, but that's in another issue.

2018-05-16 16:53 GMT+02:00 Jaap Blom <notifications@github.com>:

**Comment by jblom** [comment]
Thanks for your clear answer. Yeah d3 is very tricky indeed and really more for when you _have_ to use JavaScript (on a regular website). In case you do need to visualise something for a web site/app there are lots of libraries that use d3 under the hood and have a simple programming interface (haven't investigated in a while, so wouldn't be able to recommend one on the spot).

**Comment by mwigham** [comment]
Thanks, I'll add that to my list to look at.  I would be very pleased if
there is a way to get more interesting visualisations without javascript...

2018-05-17 7:39 GMT+02:00 Jaap Blom <notifications@github.com>:
