### ISSUE TITLE
Result list: when you click back button result list and query is gone. 

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#38]

**Comment by jblom** [comment]
I've now added a button for each search result that will open a pop-up showing the user details without leaving the page (this is actually also how it works in AVXL)

**Comment by lilimelgar** [comment]
Nice! this preview works very well, but still a user may click on the item in the result list instead of on the preview icon, and then going back the query is still gone.

**Comment by lilimelgar** [comment]
Could an option to solve this be to disable the link from the result itself, but only allow linking to it from the eye icon viewer -adding a link to "detailed record" -option to open in a new window)?

**Comment by jblom** [comment]
Interesting option for circumventing the actual problem for now. I'll consider it

**Comment by lilimelgar** [comment]
It is the same issue as #49
