### ISSUE TITLE
As a developer, I need to calculate useful statistics on metadata completeness for a given metadata field, for a given slice of the archive

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#385]
- [ ] Identify possible statistics
- [ ] Develop the necessary queries for calculating the statistics
- [ ] Discuss the statistics with the researchers
- [ ] Improve the statistics based on feedback

**Comment by jblom** [comment]
@mwigham please merge this issue with https://github.com/clariah/wp5_mediasuite/issues/386 since it is just a prerequisite of the implementation and thus can be mentioned in the description of that issue. (all with the goal of reducing the amount of GH issues...)
