### ISSUE TITLE
As a developer, I need to understand the structure of the B&G archive

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#388]
Although the idea is not to show this structure to the user, it is necessary to understand this structure in order to write the correct queries to produce the overview

- [ ] Read documentation
- [ ] Talk to archive experts
- [ ] Explore archive via Media Suite, immix/Daan, enz.

**Comment by jblom** [comment]
@mwigham closing this one as well, since it's more of a personal note
