### ISSUE TITLE
As a developer, I need to calculate statistics that give an overview of the content of the archive

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#389]
- [ ] Identify possible statistics
- [ ] DEvelop the necessary queries for calculating the statistics
- [ ] Discuss the statistics with the Media Suite researchers
- [ ] Improve the statistics based on their feedback

**Comment by jblom** [comment]
@mwigham please merge with https://github.com/CLARIAH/wp5_mediasuite/issues/391
