### ISSUE TITLE
As a developer, I need to create visualisations that give an overview of the content of the archive

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#390]
- [ ] Identify possible visualisations
- [ ] Program the visualisations in Jupyter notebook
- [ ] Discuss the visualisations with Media suite researchers
- [ ] Improve the visualisations based on the feedback

**Comment by jblom** [comment]
Please also add this in form of an issue, describing an actual implementation goal, to #397 . Closing this
