### ISSUE TITLE
As someone who is unfamiliar with the B&G archive (e.g. Media Suite user) , I want to have statistics and visualisations that give me an overview of the content of the archive

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#391]
Not the details of how the archive is structured, that isn't interesting for the user.  A more detailed overview of what is in the archive than at present in the Collection Inspector. E.g. how much TV, how much radio, how much in each genre, how much from each decade.  Also how metadata values vary over time.  Prototype functions developed in Jupyter notebooks will be evaluated and, where useful, will be added to the Collection Inspector

Deliverable: software that generates the statistics and visualisations.  Acceptance criteria: Media suite user finds the statistics and visualisations helpful in their use of the Media Suite.

**Comment by mwigham** [comment]
One possible visualisation is that discussed in #151

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #64](https://github.com/beeldengeluid/labs-search-api/issues/64) via [**ZenHub**](https://www.zenhub.com/)
