### ISSUE TITLE
As an archive institute, I want to map my metadata model to aggregated versions

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#395]
This could also form part of a non-Clariah epic to map the B&G model to various other models, and to different aggregation levels, to support users with different levels of expertise and differing tasks.

**Comment by jblom** [comment]
I am closing this, not because I don't appreciate this, but because it is something that is a bit too generic as an issue. Also this could be a non-issue since every institute is free to publish multiple models in CKAN (which in turn could be imported into the MS).
