### ISSUE TITLE
As a Media Suite user, I want to be presented with a selection of metadata fields that are understandable and relevant for me

### ISSUE THREAD

**Issue by mwigham** [CLARIAH/wp5_mediasuite#396]
The user needs to select metadata fields while searching, or defining visualisations.  What is understandable and relevant depends on the user and the particular task they are carrying our.  For example, one user may be content with searching on 'date', while another may want to determine a specific type of date field to search on (e.g sortDate).  The user should be offered the choice between simplified/aggregated fields, or more specific, with documentation on the fields to help them choose.

Deliverable: Metadata field selector in the Media Suite that allows users to choose different levels of metadata fields, and to browse documentation of the fields.  Acceptation criteria: Media suite user finds it easy to use, and it helps them in their choice of metadata field.

**Comment by mwigham** [comment]
Related to #142

**Comment by jblom** [comment]
@mwigham merged this with #142
