### ISSUE TITLE
As a scholar, I want to to be able to sort the drop-down list of metadata by ‘recommended by the data owner’

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#404]
This applies to B&G collection first:

In the [metadata dictionary of B&G fields](https://docs.google.com/spreadsheets/d/1ketKQ5h78uogx9gFZ6S2vnou90172OITqkuLt9N28mo/edit#gid=0) there are two columns (D and E) that indicate how recommended the field is to be used for search purposes. This issue consists on implement an automatic way of ordering the metadata fields in any drop-down list where they appear (in the Collection inspector and in the Search tool) by this ranking option (default), as well as alphabetically.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #45](https://github.com/beeldengeluid/labs-search-api/issues/45) via [**ZenHub**](https://www.zenhub.com/)
