### ISSUE TITLE
As a user, I would like to be able to rename bookmark groups and reorder my bookmarks in the workspace

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#407]
Once the user has created the bookmark lists/groups, these cannot be added/edited in the work space, the user wants to edit and create new group categories and reorder the bookmarks into those categories by moving bookmarks from one list/group to another. ToDos:

- [ ] Enable creating a new bookmark category in the Workspace (bookmark view)
- [ ] Make it possible to edit the name of a bookmark category/group in the Workspace (bookmark view)
- [ ] Make it possible to change the bookmark category/group of one bookmarked item (or fragment) in the workspace bookmark view
- [ ] Make it possible to "move" one bookmarked item or fragment to another user project

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #161](https://github.com/beeldengeluid/labo-components/issues/161) via [**ZenHub**](https://www.zenhub.com/)
