### ISSUE TITLE
As a scholar, I would like to have ordering options and data download option in the facet fields

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#416]
(this issue was split from #354, **see diagram there**). 

The Facet boxes implemented in #107 need the following improvements:

- [x] 1. A-Z ordering option icon: this is to order the items inside the facet alphabetically.
- [x] 2. Frequency option icon: this is to order the items inside the facet per number of occurrence.
- [x] 3. Download icon: this is to allow the user to download a CSV file with the name of the facet, the value of each facet, and the number of occurrences for the facet at the time of the query. These data should include all terms in the list (see issue #358).

**Comment by jblom** [comment]
I just removed the limit of 20 results per facet (that was an ancient setting! :s) Now the limit is set to 100000 (a limit is mandatory for ES)

**Comment by lilimelgar** [comment]
Tested on production version during summer school. Users really liked it!
