### ISSUE TITLE
As a scholar, I would like to see the content of some metadata fields in the EYE Desmet film collection properly parsed

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#418]
The current import of the Desmet film collection has some issues in the parsing of the content of some metadata fields, e.g., actors:
![screen shot 2018-05-17 at 13 54 18](https://user-images.githubusercontent.com/8133228/40175863-d6074ce0-59d9-11e8-958b-32da0b771f48.png).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #172](https://github.com/beeldengeluid/labo-components/issues/172) via [**ZenHub**](https://www.zenhub.com/)
