### ISSUE TITLE
As a scholar, I need to be able to identify in the result list which items I have already bookmarked

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#419]
When scholars are building their corpus, they would like to be able to visually identify which items have been bookmarked already in the result list, so they don't have to inspect them again. This could be solved by adding a "star" icon (bookmark icon) next to the items in the result list, which turns on or off depending on it being or not bookmarked.

**Comment by jblom** [comment]
note that an item can be bookmarked multiple times (per different bookmark group), so a "star" would not be a sufficient solution. 

More importantly, I'd say, the bookmark group & annotation model as a whole need to be reconsidered before working on this issue

**Comment by lilimelgar** [comment]
When inspecting the result list, it may not be so important to know in which bookmark group an item was included. It helps in the selection just to know if it was bookmarked or not before, perhaps then just automatically checking if it was bookmarked the selected/active user project?

About revising the model, yes! we should work on this. 

The issue is then put in the Icebox.

**Comment by jblom** [comment]
good point, but indeed let's wait with a solution after revisiting the model

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #179](https://github.com/beeldengeluid/labo-components/issues/179) via [**ZenHub**](https://www.zenhub.com/)
