### ISSUE TITLE
As a user, I need to compare the results of different saved queries

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#420]
Implement the Comparative Search tool using Saved queries:

- [x] Create a link in the "Add query" button to the Single Collection search
- [x] Add the Select project button that is in the Single Search tool now:
![screen shot 2018-05-30 at 19 08 40](https://user-images.githubusercontent.com/8133228/40735956-e56171bc-643c-11e8-84fa-34ca875b9099.png)
This button will have a different label (but same functionality) here: "Add saved query"
- [ ] Add to the drop-down list of this menu the list of existing projects, plus the number of queries existing per project. This number of queries can be taken from the Workspace/user projects/project x/Saved queries. The resulting list will be something like this:
  Bookmark-tests (0)
  Deze keer is het voor het echie (10)
  Liliana test jan24 (0)
  Metro films (3)
- [x]  When the user clicks on a user project that has saved queries (e.g., Metro films above), display the list of queries from that project. What the user will see in the Comparative search tool will be a list of saved queries (also appearing in their workspace - queries), plus an option to combine them with basic boolean operators, e.g., Query 1 AND Query 2, or Query 3 OR Query 4. See sketch:

![screen shot 2018-05-28 at 09 28 03](https://user-images.githubusercontent.com/8133228/40602638-a540fc36-6259-11e8-91f9-6a760a502b60.png)

- [ ] Solve issue #353 : allow users to create new user projects from the pop-up window for selecting user project

**Comment by jblom** [comment]
@lilimelgar how about opening the single search in a popup (for adding queries), just like it works for opening resources in the workspace? That way you could add a new query on the same page and you'll be back on the comparative search page right away

**Comment by lilimelgar** [comment]
@jblom Yes, sounds like a very good idea. The only concern is that the Single Search has also pop-ups inside (for viewing the resource: preview and opening a resource), how would this work?

**Comment by lilimelgar** [comment]
Tested on July 18, mostly done, pending thing added as new issue: #476.
