### ISSUE TITLE
As a user, I need to see alternative texts on mouse-overs for for all icons in the media suite

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#433]
- [x] Fix the display of label of date field in the icon for ordering results per date in the result list of the OH collection, it shows now: "Sort by: null" 
- [x] Improve visibility of call-to-action (CTA) button (question mark) pointing to documentation in every page

**Comment by jblom** [comment]
this is fixed in master only btw

**Comment by lilimelgar** [comment]
Tested in Master, alles goed. 
@jblom: Perhaps an option for always including the order per date button even if no date field has been selected by the user is to choose the default date per collection (we listed those in issue #444). I moved this to Q&A until we talk about what is best.
And yes, the info buttons are all there :)

**Comment by jblom** [comment]
closing this one, since it seems to be done @lilimelgar ?
