### ISSUE TITLE
As a scholar, I need to see the composition of a Saved query (collections, search terms, etc.) in the Workspace and in the Comparative search tool

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#440]
Adding more information about the parameters to the query details in the workspace.

The parameters that are indicated in the query (search string, field cluster, date field + range, filter from facet) are properly remembered when the query is replayed :), however, these parameters are not shown in the details of the saved query (I added my parameters in the title as a solution for remembering them myself as a user -the query does):

![screen shot 2018-03-27 at 11 09 46](https://user-images.githubusercontent.com/8133228/37957983-91e906cc-31af-11e8-88a5-b8d174d3462c.png)

**Comment by lilimelgar** [comment]
This issue is not solved yet. Ideally, users can see more details about the query composition in the Workspace (the same information displayed in the boxes under the graphic in the Compare tool). This is what a user sees now:

![screen shot 2018-07-16 at 16 14 11](https://user-images.githubusercontent.com/8133228/42763464-6dda4852-8913-11e8-9436-2b6827501aa0.png)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom 
Tooltip per saved query to displayed query parameters:
pull request:
https://github.com/beeldengeluid/labo-components/pull/115
branch: task/#440-expose-saved-queries-in-project-table

![Screen Shot 2018-08-21 at 13.51.59.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/9514a31b-bd06-45fa-b387-3f17abdf3ff4)

**Comment by jblom** [comment]
@lilimelgar I'd say this is done. What @avlisodraude implemented works well? Can you close this after you have tested this as well?

**Comment by lilimelgar** [comment]
This is done for now, tested in test version with different queries and collections. I close it for now, and will add forthcoming improvements as separate issues.
