### ISSUE TITLE
As a developer, I need to save favourite aggregations/facet views to the work space

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#441]
When a custom facet is added (e.g., "colour") to the query, and a filter is used from that facet (e.g., "zwart/wit") (see image 1), and the query is saved and replayed, the results bring back the correct filter (see "zwart/wit" in the image), but the facet itself is not remembered (see image 2).
Image 1: 
![screen shot 2018-03-27 at 11 20 40](https://user-images.githubusercontent.com/8133228/37958479-ec5ffd80-31b0-11e8-9b1b-7c5721dcd750.png)
Image 2:
![screen shot 2018-03-27 at 11 20 17](https://user-images.githubusercontent.com/8133228/37958487-f365b58e-31b0-11e8-970f-701fd6163313.png)

This issue originates from solving #152 (creation of user aggregations/clusters)

**Comment by jwassenaarbg** [comment]
Have put a pull request for this and #349
