### ISSUE TITLE
As a developer, I need to save favourite field clusters to the work space

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#442]
Acceptance criteria:
- after making a custom field cluster, there is an option to save it as within the active project
- after saving the saved cluster appears as a new tab next to the "saved queries" in the workspace
- in the new overview of saved clusters, it is possible to delete or edit clusters

**Comment by jblom** [comment]
moved it to CLARIAH+ for now, since I'm reluctant to implement new features to the workspace before remodelling the space as a whole.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #137](https://github.com/beeldengeluid/labo-components/issues/137) via [**ZenHub**](https://www.zenhub.com/)
