### ISSUE TITLE
As a scholar, I need extra functionalities for excluding terms in facets when creating my corpus

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#443]
Currently, the list of terms in the Facets (Single Search tool) is based on positive selection, but it is not possible to exclude terms. This is important when creating a corpus.

**Comment by jwassenaarbg** [comment]
@lilimelgar The ability to exclude items from facets has been introduced in branch 443, which awaits review from Jaap

**Comment by jblom** [comment]
@jwassenaarbg please reimplement this in the updated search API and using a simple checkbox in the UI

**Comment by lilimelgar** [comment]
@jwassenaarbg I am testing this in Master, is that correct? or which branch should I use for testing?

**Comment by jblom** [comment]
@lilimelgar this was already merged with master, you can check it out.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #175](https://github.com/beeldengeluid/labo-components/issues/175) via [**ZenHub**](https://www.zenhub.com/)
