### ISSUE TITLE
As a user, I expect to see a video/audio item for all records in the Oral history collection that have a view (open eye) icon next to them

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#447]
Currently, in the OH collection, if you click on the facet "open access", you get around 200 items that can be played. But this is not detected, and the Eye icon remains closed ;)

**Comment by jblom** [comment]
I fixed this on test. You only get closed eyes when the video file is absent.

**Comment by lilimelgar** [comment]
Fantastic! more than 200 open eyes! (tested in test version, June 20). There are a few that result from the filter "open access" which have closed eye, with no video/audio file indeed, so, closed eye is logic, but I wonder why the media didn't come available. But this is for another issue, for now, done!
