### ISSUE TITLE
As a scholar, I would like to see an icon indicating the level of an item in my result list (complete item, segment)

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#45]
Together with icon showing media type, would be useful to see which level the result corresponds to: series, programma (expressie), segment, e.g, in the case of B&G collection: display "Soort" (level) in snippet view.

**Comment by lilimelgar** [comment]
It appears for B&G collection now (small icon showing when it is a fragment). Further issues will be reported per collection.

**Comment by lilimelgar** [comment]
This issue needs discussion and more clear requirements. @mwigham: could we look at this later please? For now in Icebox.

**Comment by jblom** [comment]
This is a complicated issue and should be addressed in CLARIAH+

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #136](https://github.com/beeldengeluid/labo-components/issues/136) via [**ZenHub**](https://www.zenhub.com/)
