### ISSUE TITLE
As a developer, I need to fix the problems with display of metadata completeness for the Desmet film collection

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#471]
In the Inspector tool, all fields from EYE Desmet film collection show 100% completeness (see image below). It seems that the empty fields were not detected as such:

![screen shot 2018-07-16 at 15 40 04](https://user-images.githubusercontent.com/8133228/42761722-a1aa1bd0-890e-11e8-88ec-c2a623605724.png)

Besides, there are some field names not properly parsed (see image below)

![screen shot 2018-07-16 at 09 46 55](https://user-images.githubusercontent.com/8133228/42748408-66cf5c92-88e0-11e8-916c-5c1f10981c2d.png)

(issue came from summer school test)

**Comment by jblom** [comment]
@wmelder @jwassenaarbg this can be fixed by reindexing: empty strings should become null values instead

**Comment by jwassenaarbg** [comment]
I fixed this for the paper collection, should I do the film collection as well @wmelder ?

@jblom the index is eye-desmet-papers3

**Comment by wmelder** [comment]
must be fixed within the current importer, otherwise the fix will disappear whenever the data is refreshed (new import with improved date filters)

**Comment by lilimelgar** [comment]
I checked the Desmet paper collection in the test version of the Inspector (October 10), and the index is correct now (Desmet papers 4). Still pending @wmelder is to fix the Desmet film index.

**Comment by wmelder** [comment]
This issue is fixed by replacing empty strings with null values in the importer. Also the updater (needed for the date normalisation) is fixed, because it couldn't handle null values ;-)
De eye-desmet-affiches (or poster collection) suffered the same problem and is also fixed.

**Comment by lilimelgar** [comment]
Tested on master, alles goed!
