### ISSUE TITLE
As a user, I want to see what the fields of the Desmet paper collection mean

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#472]
Add definitions of fields to the Desmet paper collection in the Collection Inspector. Most urgent, add definitions of date fields:

![screen shot 2018-07-16 at 10 18 48](https://user-images.githubusercontent.com/8133228/42748768-aa36a9d0-88e1-11e8-8e8a-6a04305a2402.png)

@jwassenaarbg: Could you please add below the name of the column in Excel that you used for this date fields?: 

Current label | Column from original excel file:
------------ | -------------
coverDescriptionYear => folder | 
coverPeriod => folder | 
groupCoverPeriod => folder | 
gte => folder.coverDescriptionDate | 
Ite => folder.coverDescriptionDate | 
mostSpecificDate => folder | 
subCoverPeriod => folder |

**Comment by jwassenaarbg** [comment]
@lilimelgar I updated the descriptions for this collection view the file here: http://rdbg.tuxic.nl/clariah/eye-desmet-papers2

They will be visible when @jblom updates the config.

**Comment by jblom** [comment]
I published this on test (+ all of todays issues I dragged into the "test column" can be tested on test)

**Comment by lilimelgar** [comment]
@jblom I don't seem to get the updated labels mentioned by Johannes in neither version (Test or master branch)...

**Comment by jwassenaarbg** [comment]
Can you see the labels now? I was able to view the labels after pulling.

**Comment by lilimelgar** [comment]
@jwassenaarbg I can see the dictionary in the Inspector (very useful!). Two suggestions:
(1) Please update the field names to make them more user-friendly
(2) Please update the field definitions

The new data for both updates is included in [this file](https://docs.google.com/spreadsheets/d/1ef2HAWnozgL1Xm4GVTLTYlQVKpdf1r7LZqW0TQVYFPs/edit?usp=sharing).

For later:
-Try to present the metadata in the resource viewer (all data) in a more meaningful order (alphabetically or in logical order depending on the collection).

**Comment by jblom** [comment]
@lilimelgar is this done yet?

**Comment by jwassenaarbg** [comment]
@jblom I'm working on the suggestions above, not yet finished.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #169](https://github.com/beeldengeluid/labo-components/issues/169) via [**ZenHub**](https://www.zenhub.com/)
