### ISSUE TITLE
As a developer, I need to make sure that all CKAN collections that should show up in the collection selector are properly imported via the importing pipeline

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#474]
"Using the MSDataManager CSV importer, probably use the to-be-created dataConverter" is the only task not done for the Epic about making the Desmet paper collection available (#293). The import was done separately with a script.

This issue is about making sure that all CKAN collections that should show up in the collection selector are properly imported via the importing pipeline

Note from Jaap (July 18): I would also suggest to wait with this, since it is an issue that will probably linger for a while).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #51](https://github.com/beeldengeluid/labs-search-api/issues/51) via [**ZenHub**](https://www.zenhub.com/)
