### ISSUE TITLE
Implement relative values in bar chart 

### ISSUE THREAD

**Issue by avlisodraude** [CLARIAH/wp5_mediasuite#475]
As I user I'd like to be able to switch between absolute and relative values in the bar chart as it is done in the line chart.

**Comment by avlisodraude** [comment]
@jblom @lilimelgar : pull request for this issue has been created at:
https://github.com/beeldengeluid/labo-components/pull/103

**Comment by jblom** [comment]
@avlisodraude when switching to **relative** the number of records shown in the chart is updated; when switching back to **absolute** this number is not changed back.

Could you fix this please?

**Comment by lilimelgar** [comment]
@avlisodraude: tested in Master. The switch works well and values are updated in the chart (points per year). However, the value corresponding to the number of records for the query doesn't always update:

![screen shot 2018-08-14 at 15 01 53](https://user-images.githubusercontent.com/8133228/44093245-481c444a-9fd3-11e8-9d43-a69dc3a71476.png)

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :
Issue regarding total number of hits being changed when changing from absolute to relative values in Histogram has been solved.
The changes are in the branch called: 
task/#475-fix-relative-number-in-histogram

Pull request:
https://github.com/beeldengeluid/labo-components/pull/113

**Comment by jblom** [comment]
checked it and it seems ok. The number now stays the same

**Comment by lilimelgar** [comment]
Yes, it works Ok. @jblom: do I close it? or do we wait until you merge the changes?

**Comment by jblom** [comment]
I'll close it. This has been merged
