### ISSUE TITLE
As a user, I would like to see in the Comparative tool, which of my projects have saved queries

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#477]
In the Comparative tool, when the user clicks on "Set project" s(he) should see in the drop-down list of projects the list of existing projects, plus the number of queries existing per project. This number of queries can be taken from the Workspace/user projects/project x/Saved queries. The resulting list will be something like this:
Bookmark-tests (0)
Deze keer is het voor het echie (10)
Liliana test jan24 (0)
Metro films (3)

This is to make it easier for users to know if their projects have queries they can compare.

**Comment by lilimelgar** [comment]
@jblom: is it too complicated to show the number of queries only in the project list that is shown in the Compare tool? at the moment, the number of queries is also displayed in the project list in the Search tool. This is normal since it is a component but, there in the Single search the user may not be interested on knowing the number of queries.

**Comment by jblom** [comment]
@lilimelgar so this should be done already by @avlisodraude (for quite a while?). Putting this issue test

**Comment by lilimelgar** [comment]
Yes, tested in test version, works well!
