### ISSUE TITLE
As a user, I need to see the media type of the items in the result list, so I can get a better overview of which type of media is part of my result and choose the relevant ones at first sight

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#48]
Currently, there is an icon appearing next to each result in the result list:

![screen shot 2018-01-22 at 15 38 59](https://user-images.githubusercontent.com/8133228/35226058-6773fb2e-ff8a-11e7-9c3f-19418eecdbb0.png)

The use of this icon has changed over time: initially (version 1) it was used to show which items could be played. Currently (January 2018) there are two issues to solve:
-Agree upon the use of this icon: is it to show always which media type the item belongs to regardless of whether it can be played/viewed or not, or leave it only for playable items
-Check that all collections have this detection: Update config.file to detects and display media type icons for available collections. 

The comments below trace this history and propose solutions.

**Comment by lilimelgar** [comment]
Mostly solved for B&G collection. Will report other issues per collection later.

**Comment by lilimelgar** [comment]
Willem says: 

Does the media icon mean that it is playable?
When looking at the Collectie Diederichs data it's obvious that there's no open media available, although a field with media types exists:

mods:internetMediaType:Array[3]
0:"text/pdf"
1:"text/doc"
2:"sound/wav/mp3"

See this note:
mods:note:"Alleen toegankelijk voor wetenschappelijk onderzoekers. Onderzoekers die interviews willen inzien/beluisteren, moeten een schriftelijke aanvraag indienen bij Aletta, instituut voor vrouwengeschiedenis. Onderzoekers krijgen toegang tot (een gedeelte van) de interviews onder voorwaarde dat bij publicatie (in welke vorm dan ook) de anonimiteit van de geïnterviewden en hun nabestaanden gewaarborgd is. Onderzoekers worden verplicht hun publicatie vooraf ter inzage te geven aan Aletta, instituut voor vrouwengeschiedenis, zodat gecontroleerd kan worden of de anonimiteit gewaarborgd is."

**Comment by lilimelgar** [comment]
The icon does not necessary indicate that is playable (it isn't clickable), but it informs about which media type it is. Thanks, we will check this in detail for V2.

**Comment by jblom** [comment]
Just to clarify how this works. In the MS it is possible to add a configuration file for each collection (if not, a default is used). Amongst several other things, this config takes care of assigning a media type to each item by trying to distill information from the raw metadata.

So this issue is all about optimising these configurations as well as more thoroughly inspecting the raw metadata of each collection (in order to find these media types).

**Comment by lilimelgar** [comment]
What tasks are there to do for optimizing the configuration files?

**Comment by lilimelgar** [comment]
Tested in version 2:
-Icons showing media types work quite well in B&G collection(s) (few items non-identified)
-icons do not show in Desmet film collection
-icons do not show in Desmet poster collection
-icons do not show in KB newspapers
-icons work/show well in Open images EYE
-(not possible to test in Open images B&G -not working at time of testing)
-icons do not show in OH aggregated collection

**Comment by jblom** [comment]
Desmet film & poster already worked properly. The thing is that there are just not a whole lot of resolvable/playable links for the content. For Desmet film I guess we still can reconsile some additional youtube links from the old index.

**Comment by jblom** [comment]
Ok all collections are now properly configured. So the icons in the result list mean if there is actually content (of a certain media type) that you can see (and play) on the detail page. 

So if there is no icon, it means that no content can be shown in the media suite regardless what the situation is in the source catalogue (where things might be accessible behind a login or whatever).

**Comment by lilimelgar** [comment]
This works well  in the test with Desmet film, Open images (eye, b&g) and B&G.

However, I notice we are mixing two issues here:
1) show icons indicating the media type (this has to do with issue #260 ) no matter if they can be played or not
2) show an icon indicating if the items can be viewed or played, this is an access/no access icon. This icon should be always present and have a sort of X or cross line to show when the item cannot be played/accessed. This applies to media objects only (not to entities for instance). This is issue #165. 

The ideal solution is that ALL records have an icon showing media type PLUS an icon indicating Access/No access.

**Comment by lilimelgar** [comment]
@roelandordelman. I described it more clearly now.

**Comment by jblom** [comment]
Hi both,

I agree with what is suggested. 

For this to work we probably need to add an extra field in the collection mappings so that we can configure: "All items in KB are media type: image", "all items in DANS are media type: video". This is needed since it cannot always be derived from the metadata what a record represents.

Anyway. I think we'll need to put this one again in the next sprint for me to finish it.

**Comment by jblom** [comment]
@lilimelgar I've added a separate access icon to each search result. Now also the media type is shown at all times (it can also be unknown, depicted by a question mark).

On the collection level I've added a config option to specify the default media type (nothing to test about this, but just FYI)

A different story is incorporating the media type as a default field in all collections, so it's possible to create a facet for this. This is another job and should be done whenever we're ready to take incorporating a basic schema on import (@wmelder).

**Comment by lilimelgar** [comment]
Tested on Master (Feb.5). I summarize here what I found (each request to improve is entered as separate issue), this one can be closed.

-B&G: OK! there are some icons that display image type + access option (e.g., 4937317@program), but since the images are not made available yet, they cannot be viewed. We could add on "mouse over" in those cases: item can be viewed but it's not available in the MS yet, or something like that (added issue #302)
-Desmet films: OK
-Desmet posters: OK
-KB newspapers: It is displaying two media types for the same objects: Unknown and Image
![screen shot 2018-02-05 at 11 18 23](https://user-images.githubusercontent.com/8133228/35799528-4f50b938-0a66-11e8-9f90-ec62a0bd7a4e.png) (added as issue #303)
-Open Images (EYE): OK. Strange that a couple of items have no access (I'll look at this in future testing, for now OK).
-Open Images (B&G): OK
-DANS OH: OK
-Radio B&G: OK
-TV B&G: OK

I agree with the suggestion to include "media type" in the mappings, so it is possible to filter per media type when searching. This is in issue #260.
--
Small suggestions:
-Change the icon from an open eye to another icon (for instance something like a play button?), this is because there is another "eye" icon to view the metadata, same icon for two different functions may be a bit confusing. Another option is to change the other Eye icon for the metadata view on the left into a little "metadata card" or something like that (magnifier glass icon should be reserved for the Inspecting functions). Issue #304.
![screen shot 2018-02-05 at 11 00 58](https://user-images.githubusercontent.com/8133228/35798703-e4cf3a14-0a63-11e8-8b40-aef8fa9769b0.png)

-Text on mouse over in question mark says: "Unknown content", perhaps it is more clear to say: "Unknown content type"? We leave this for now, I'll add it if users suggest the change in future tests.

**Comment by jblom** [comment]
On the master I changed the quick-view eye button to a sheet-of-paper-with-text on it. Not sure if that is the best one, but at least it allows for keeping the open & closed eye for conveying the accessibility.

I changed the mouse over to Unknown content type.

I'll check the other things in your new issues
