### ISSUE TITLE
Fix broken link to Documentation pages

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#481]
The link to the Documentation pages from the About page is broken, needs to delete slash from URL:

http://mediasuite.clariah.nl/documentation/
http://mediasuite.clariah.nl/documentation

![screen shot 2018-07-16 at 16 56 29](https://user-images.githubusercontent.com/8133228/42765850-3c5e35f8-8919-11e8-95b2-13da8e0d02c2.png)

![screen shot 2018-07-16 at 16 57 01](https://user-images.githubusercontent.com/8133228/42765875-4b600810-8919-11e8-9249-b9d7ddf7f937.png)

**Comment by jblom** [comment]
@lilimelgar is this done?

**Comment by lilimelgar** [comment]
Yes, done!

**Comment by lilimelgar** [comment]
This has been fixed, also in production version.
