### ISSUE TITLE
Add search box for NEW facets (Create new aggregation)

### ISSUE THREAD

**Issue by avlisodraude** [CLARIAH/wp5_mediasuite#482]
Add search box for NEW facets (Create new aggregation) to filter out results while typing
![Screen Shot 2018-07-17 at 08.57.32.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/f1791ee0-6f40-4780-b92e-782172bc8ba7)

**Comment by lilimelgar** [comment]
@avlisodraude  is this the same as #321?

**Comment by jblom** [comment]
indeed same issue as #321 and @avlisodraude solved this. It's in the master, ready to be tested

**Comment by lilimelgar** [comment]
Tested on Master with different collections. Works well!
