### ISSUE TITLE
As a developer, I need to fix bug in the result list pagination

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#483]
When clicking on going to last page in the result list, one gets an empty page. See [screencast](https://drive.google.com/open?id=1nkeY-Z7MvxRQd6MMbXw3P58EpyT9g6fi).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #63](https://github.com/beeldengeluid/labs-search-api/issues/63) via [**ZenHub**](https://www.zenhub.com/)
