### ISSUE TITLE
As a user, it would be easier to have the facet field name written automatically when creating a new facet

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#484]
In the Search tool, when users create a new facet, the name of that facet has to be added manually. It could be useful to assign automatically the name of the field that was selected for the facet. But the option to edit the name should still be there.

**Comment by jblom** [comment]
@avlisodraude implemented this. It can be tested in the master. The only thing that needs to be improved is that the metadata fields, and thus the automatically created facet labels, are pretty long for e.g. B&G.

Let's see how to solve this nicely

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #165](https://github.com/beeldengeluid/labo-components/issues/165) via [**ZenHub**](https://www.zenhub.com/)
