### ISSUE TITLE
Upgrade Mediasuite to Webpack V4 

### ISSUE THREAD

**Issue by avlisodraude** [CLARIAH/wp5_mediasuite#489]
Upgrade Mediasuite to Webpack V4 and all its dependencies. Also update code accordingly. 
This will be done for both (Labo-components & wp5).

**Comment by avlisodraude** [comment]
@jblom labo-components has been updated to webpack v4 along with all the changes reported during the compilation process. Unfortunately the webpack.config file is not 100% done (some cleaning and proper mode configuration is required). 
wp5 has only been updated for react react-dom to v16. Webpack is still on V3 (monday job).
Both branches are named as this issue (#489)

**Comment by jblom** [comment]
@avlisodraude closing this one. We can make a new issue for upgrading the media suite to webpack 4 later
