### ISSUE TITLE
Improve "detailed resource viewer"(s) and the result list

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#49]
==summary of this request:
1. Delete eye icon
2. Make description-metadata viewable only if you click on an arrow icon (expand-collapse) that shows the information-metadata that currently pops-up when people click on eye icon)
==
In the search result list of the Comparative search and Multi-layered Single collection search recipes, you find two options to get the detailed record (i.e., the "detailed resource viewer"): (option 1) clicking on the "eye" icon, or (2) clicking on the title itself:

![screen shot 2017-07-20 at 10 57 19](https://user-images.githubusercontent.com/8133228/28409222-3adea5d8-6d3a-11e7-986c-85f8d3eab9b2.png)

**Problem 1**: When clicking on the icon (option 1), a pop-up window shows up, which you can close with the X on top. But, when you click on the title (option 2) you see the detailed record, and when you hit the back button, your query disappears. 
Solution to problem 1: What is needed is that the query and the result list stays after going back from the detailed record view to the query.

**Problem 2**: When the user clicks on the "eye" icon (option 1) she gets a pop-up window with the metadata, and the option to play the media at the end of this window:

![screen shot 2017-07-20 at 12 04 24](https://user-images.githubusercontent.com/8133228/28412183-a2c629ec-6d43-11e7-8286-60f2dc98574e.png)

When the user clicks on the title itself (option 2), she gets the media first (with video display and active annotation functionalities), and the metadata ("all data") below the media file:

![screen shot 2017-07-20 at 12 09 33](https://user-images.githubusercontent.com/8133228/28412380-5a5dc524-6d44-11e7-8e87-8a3889f55c64.png)

The problem here is that the user finds two ways of arriving to the "detailed record view" and to the resource, while it would be more clear to present only one.

The proposed solution for problem 2 is:

1) When the user is inspecting the result list, she finds an arrow (collapsible menu) or tab to display the metadata for each individual under the result, without being prompted to any pop-up window or extra window outside the search results. Example from Scopus database, with collapsible menu when clicking on "view abstract"):

![screen shot 2017-07-20 at 12 11 53](https://user-images.githubusercontent.com/8133228/28412492-a807a416-6d44-11e7-8e27-1dc7d90d6f92.png)

![screen shot 2017-07-20 at 13 10 03](https://user-images.githubusercontent.com/8133228/28414632-e0c7b662-6d4c-11e7-8f3d-99d0b02715e9.png)

Another example from the UvA library catalog with a "Details" tab:
![screen shot 2017-07-26 at 11 12 03](https://user-images.githubusercontent.com/8133228/28613717-7aee1600-71f3-11e7-827a-d93542a11faf.png)

This embedded display can be more clear than the current pop-up window.

2) Then, if the pop-up window is replaced, the Eye icon disappears, and the user can arrive to the detailed record view of individual search results only in one way: e.g., clicking on the title in the search result:

![screen shot 2017-07-20 at 13 14 28](https://user-images.githubusercontent.com/8133228/28414778-64d4a53c-6d4d-11e7-8151-6f13df8954b6.png)

**Comment by lilimelgar** [comment]
It is the same as #38

**Comment by avlisodraude** [comment]
@lilimelgar Issue done and merged into Master branch.
Github details at:
[Code changes](https://github.com/beeldengeluid/labo-components/commit/ffcf6885d6fc7446a833f08ad0a6e03b900625cb)

**Comment by lilimelgar** [comment]
Tested in master branch, Single search and Comparative search. OK
Next steps (add links between summary view and detailed view) in another issue.

**Comment by lilimelgar** [comment]
Tested for B&G Collection, Dans-OH, Kb-newspapers, Eye-films and affiches.
