### ISSUE TITLE
Fix link to Login in footer

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#496]
There is a small typo in the Url to the workspace in the login link in the MS footer (prod. version).

**Comment by avlisodraude** [comment]
@lilimelgar @jblom :
This issue (url typo) was already fixed in Master and the url points to the right page in the test version (http://mediasuite-test.rdlabs.beeldengeluid.nl/).
Once production gets updated this issue will be solved.
Closing this ticket.
