### ISSUE TITLE
Move compare queries action button to actionsBulk bar in query comparison

### ISSUE THREAD

**Issue by avlisodraude** [CLARIAH/wp5_mediasuite#498]
Move compare queries action button to actionsBulk bar in query comparison:

From: 
![Screen Shot 2018-08-21 at 23.44.52.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/77af0689-4f53-49ec-b33a-f9ddb3128b0d)

To :
![Screen Shot 2018-08-21 at 23.48.51.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/a5513a5d-e0b3-4157-bfd4-dc5bf4aee28b)

**Comment by avlisodraude** [comment]
@jblom : pull request: https://github.com/beeldengeluid/labo-components/pull/117

@lilimelgar : for testing use branch :
task/#move-compareQueries-btn-toactions-bar

**Comment by jblom** [comment]
this works now. Closing
