### ISSUE TITLE
As a developer, I need to fix bug in Search tool when switching to histogram type of graphic

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#499]
There is a bug in the Search tool (Master branch, August 22): when one switches to histogram, and enters a new search term, the Search tool turns empty.

See [screencast](https://drive.google.com/open?id=1iJ5SEtZ_jQwTpDaKAfoYEDF_73ihbxr0).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #184](https://github.com/beeldengeluid/labo-components/issues/184) via [**ZenHub**](https://www.zenhub.com/)
