### ISSUE TITLE
As a developer, I need to solve bug of saved queries having the same ID

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#501]
When the users save a query based on certain parameters, reply this query, and they refine the parameters and save a new query, the second query is stored with the same ID.

**Comment by jblom** [comment]
@lilimelgar I fixed this in the master, could you test?

**Comment by lilimelgar** [comment]
@jblom: I tested in master (Sept.4 update), but there is still the issue that if you replay a query that you save and you make changes to it, and save it again, the ID is the same. Thus, when you replay the query that you made based on the first one, it always gets the initial one.

**Comment by lilimelgar** [comment]
Tested in test version, works well!
