### ISSUE TITLE
As a user, I would like to see the Media Suite version number more clearly in the header

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#506]
Many users take screenshots of the Media Suite to include them in their papers/reports, but they often forget to add the version number in their captions to those images. To guarantee that we preserve "provenance" information (which software version is used), an idea is to move the version number to the header (next to the main logo), so the version number always appear in the screenshots.

**Comment by avlisodraude** [comment]
@jblom @lilimelgar :  Issue done on branch task/#506-display-ms-version-in-header from the WP5 project

**Comment by jblom** [comment]
@avlisodraude somehow the additional styling made the version number appear behind the log, I restored that, so now the version is again in the top left corner. It's merged with the master. It can be tested (also @lilimelgar )

**Comment by jblom** [comment]
(I also reindented the file to use 4 spaced tabs; imo it's now much easier to see where a block starts & ends)
