### ISSUE TITLE
As a user, I would like to copy the search parameters of my saved query

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#509]
Issue #440 was about showing the parameters of a saved query. This shows in a pop-up on mouse over. This issue is about facilitating the exporting/copying of those parameters as text, so the user can paste them in their reports/papers.

So, add a button either in the pop-up for copying, or an extra button in the query menu (now it has Delete and Open) for the same purpose.

![Screen Shot 2018-09-24 at 17.07.29.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/4e788310-5704-437a-b0e7-eb78110a6603)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #157](https://github.com/beeldengeluid/labo-components/issues/157) via [**ZenHub**](https://www.zenhub.com/)
