### ISSUE TITLE
As a developer, I need to have a clear procedure for importing metadata dictionaries

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#510]
For version 3, we used a temporary solution to have the metadata dictionary of B&G in the MS. For forthcoming versions, we should decide whether this is going to be provided via CKAN or Github, or in which other way.

--
Edited mail from Werner explaining the process (June 28, 2018)
- I convert the drive to csv to a json file in a format that can be read by the media suite.
 (latest version here: -ask Liliana )
- I have to share this file with Jaap, en he puts it in a hosting at NISV for use in the Media Suite.
To enable you to directly edit the data, we have a processing and a hosting step that needs to be resolved. :)
The easiest way to accomplish this, is to host the json file on a github were you can edit it. (Although for summer school the Jaap-hosted version is ok)  In the future - and for work on fielddescriptions on other collections - we should see then what would be the best way to make this work better.
So, I hope this clears things up. Most important thing is that, the new descriptions will be in the MS soon! :)
Met vriendelijke groet,
Werner Helmich

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #53](https://github.com/beeldengeluid/labs-search-api/issues/53) via [**ZenHub**](https://www.zenhub.com/)
