### ISSUE TITLE
As a user, I need that the numbers are shown with decimal separators

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#511]
User request to add decimal separators to hit counts everywhere. (The collection I selected has "1883516" items -- err.... is that one million+ or 188 thousand+...)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #150](https://github.com/beeldengeluid/labo-components/issues/150) via [**ZenHub**](https://www.zenhub.com/)
