### ISSUE TITLE
As a developer, I need to fix a small language issue

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#513]
Small language thingie: "Total amount of records in this collection" > "Total number of records in this collection"

![screen shot 2018-10-10 at 13 55 02](https://user-images.githubusercontent.com/8133228/46734622-21da9780-cc94-11e8-8490-164d2bf7d03c.png)

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #160](https://github.com/beeldengeluid/labo-components/issues/160) via [**ZenHub**](https://www.zenhub.com/)
