### ISSUE TITLE
As a developer, I need to check what the problem is for creating personal collections

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#514]
A user reports to have problems creating a personal collection:

<img width="871" alt="screenshot 2018-07-03 15 43 34" src="https://user-images.githubusercontent.com/8133228/46735479-a4645680-cc96-11e8-9c9c-d161ba41114f.png">

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-user-space-api #3](https://github.com/beeldengeluid/labs-user-space-api/issues/3) via [**ZenHub**](https://www.zenhub.com/)
