### ISSUE TITLE
As a developer, I need to position the annotation tool/window in a way that doesn't cover the resource

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#517]
In v3, Desmet paper collection mostly, the annotation window/pop-up covers the image, making it difficult for the user to read while annotating:

![screen shot 2018-10-10 at 15 01 11](https://user-images.githubusercontent.com/8133228/46738070-80584380-cc9d-11e8-8ac5-578a216887bb.png)

This issue is for https://github.com/hugolio (add as collaborator).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #143](https://github.com/beeldengeluid/labo-components/issues/143) via [**ZenHub**](https://www.zenhub.com/)
