### ISSUE TITLE
As a user, I would like to go to move in the list of results of the pre-selected bookmarks

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#525]
This issue complements the already implemented issue about navigating within the results list from the resource viewer, i.e., passing to the next/previous result in a list (#479). 

As suggested by Johannes, this issue consists on reproducing the same behavior above for the pre-selected list of bookmarks, which shows when clicking on "Show selected items" (implemented in issue #423).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #174](https://github.com/beeldengeluid/labo-components/issues/174) via [**ZenHub**](https://www.zenhub.com/)
