### ISSUE TITLE
As a user I'd like to get the DATE of objects returned in the right format

### ISSUE THREAD

**Issue by avlisodraude** [CLARIAH/wp5_mediasuite#526]
In some collections, ie, "eye-desmet-papers4", we get as Date field a year range (1921-1951) instead of a value. 
We mostly get back a date in the dd-mm-yyyy format.

Other cases for Date field values are 'null' 
or no Date at all when object is not found: "error: source catalogue not available"

Example of date ranges:
http://0.0.0.0:5304/workspace/projects/e604d1d6-5105-4f43-ab66-93c635c35589/bookmarks 

To properly display the data we would like a date in the dd-mm-yyyy format when available

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #62](https://github.com/beeldengeluid/labs-search-api/issues/62) via [**ZenHub**](https://www.zenhub.com/)
