### ISSUE TITLE
As a developer, I need to fix issue with KB newspaper facets displaying text fields

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#527]
This issue applies to the "Create new facet" in the Search tool, where some fields are not clear. ToDos are:

- [ ] Remove these fields the facet list (they are or should not be keyword fields): 
-ArticleBody
-ArticleTitle (or, change the label to "ArticleTitleWord", and it should be applied to all article titles, not only to a few of them
-Is part of
-paperPDFUrl
-publisher

- [ ] Change the label "paperTitle" for "NewspaperTitle", and the label "paperDate" for "NewspaperDate"

- [ ] Remove the asterisks that indicate that these fields are text fields, they are keyword fields:
-Distribution area
-Origin
-Place of publication
-SourceUrl

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #182](https://github.com/beeldengeluid/labo-components/issues/182) via [**ZenHub**](https://www.zenhub.com/)
