### ISSUE TITLE
Provide link to original record 

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#54]
To the original catalog, e.g., Immix record, from Add query-> search ->Resource viewer

**Comment by jblom** [comment]
currently there is a link to the in.beeldengeluid.nl page. Do you mean a link to e.g. zoeken.beeldengeluid.nl instead?

**Comment by lilimelgar** [comment]
I mean that in every collection (not only B&G) there should be a way to link to the "original" record in their catalog system. This requires more analysis (requirements) though.

**Comment by lilimelgar** [comment]
It is the same as #42

**Comment by lilimelgar** [comment]
Tested in Master for:

-B&G collection. Ok

-Eye Desmet films: @wmelder The link to the record at EYE's catalog is not in there, is this possible to obtain so people can go to the record in Eye's catalog if necessary? If it is not possible, please add a message that says: View in Eye's catalog: Not direct link, use the "ID" to search in eyefilm.nl

-Eye Desmet affiches: @wmelder Link to original record is missing. Perhaps add the same message than for the films.

-DANS Oral history: @jwassenaarbg: the link to the DANS record seems to be missing in all collections. If not possible to obtain automatically, add a default label/message: Source: View in DANS catalog.

-Pending to check with other collections that will be available in Version 2.

**Comment by jwassenaarbg** [comment]
For the DANS Oral History collection:
Example source: http://mediasuite-test.rdlabs.beeldengeluid.nl/tool/default-item-details?id=oai:easy.dans.knaw.nl:easy-dataset:42159&cid=dans-oral-history&st=ipnv

All documents in this index should have both an "ID" and a "dcterms:identifier" field. Both can be linked to the corresponding entry in EASY.

From the example: 
ID: oai:easy.dans.knaw.nl:easy-dataset:42159
dcterms:identifier: urn:nbn:nl:ui:13-nez-whl

@jblom : 
The ID can be used as follows: https://easy.dans.knaw.nl/ui/rest/datasets/easy-dataset:42159
The identifier field can be used with PID: http://persistent-identifier.nl/?identifier=urn:nbn:nl:ui:13-nez-whl

If needed, this transformation can be done in the XSLT phase I guess. 

Hope this helps,
Johannes

**Comment by jblom** [comment]
Hi, just now I updated the mapping for DANS oral history to include this link into the detail page:
![schermafbeelding 2017-12-12 om 11 35 23](https://user-images.githubusercontent.com/917310/33880044-99b617b8-df30-11e7-91be-b4bc430e626f.png)

I'll send you all the updated mapping, so you can see for yourself.

**Comment by jwassenaarbg** [comment]
An update to the XSLT has been made (now waiting until 17:00 because the index will be recreated for this to show up). The dcterms:identifier field now contains the link for the source in EASY.

Reason:
The dcterms:source field is already used to point to the thematic (source) collection page, not the individual data page which is meant here. This is why I made the decision to put the URL to the individual page in the identifier field.

**Comment by jblom** [comment]
The DANS source is in

**Comment by jblom** [comment]
for the EYE collections I'm showing a message, since there is no link to be found in the metadata. It's something @wmelder might figure out by looking at the source data.

**Comment by jblom** [comment]
ok I've went through all the collections and each one has now either a source link or a message on the detail page. E.g. for EYE Film: http://mediasuite-test.rdlabs.beeldengeluid.nl/tool/default-item-details?id=FLM44059&cid=eye-desmet-films&st=werk

It's deployed on test. Note: the KB collection is not available there yet

**Comment by roelandordelman** [comment]
@jblom @lilimelgar looks good, very nice!
