### ISSUE TITLE
If "not enough data for a date slider" then the "search results plotted on a time line" tab is closed by default

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#55]
Or, temporarily, maybe change message "not enough data for a slider" for something like: "Selecting data rannges is only possible when results are more than ##"

**Comment by jblom** [comment]
I changed the text for now. Solving it properly takes too much time for now.

**Comment by lilimelgar** [comment]
See other issues related to time slider (data picker): #97 , #75
