### ISSUE TITLE
It is not clear if user can get details about the metadata fields in the "Metadata inspector" of the Collection inspector recipe

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#61]
Not sure if this is a bug, please check. It is in this recipe, clicking on the little icon next to the collection name.

**Comment by jblom** [comment]
I changed the name of the stats icon to "view collection field types", so it's more clear that it's for viewing only. Also now the selected collection becomes active right after the pop-up closes, so it's more clear that you can explore/analyse the selected collection right away

**Comment by lilimelgar** [comment]
This part of the recipe has been named "Metadata inspector" in the [user manual](https://docs.google.com/document/d/1SGWMcO5w6UsAENlaBlaoVVQCB2n5TtBS8PBfdy41FSg/edit#). We should agree on the final name and keep it consistent.
