### ISSUE TITLE
Title field values in Desmet collection

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#63]
Some results from Desmet collection show a different field in the title, example: cat51823.

**Comment by wmelder** [comment]
The values like "cat26117", "cat71637", etc. are available in the dc:identifier field. As it seems, for this record the title field is empty and somehow the identifier seems to be 'promoted' to title. I guess we must look in the custom collection mappings for this.

**Comment by jblom** [comment]
ah yes, whenever I can't find a title for the result snippets, I use the identifier as title. What would be nicer is to show instead:

"no title (identifier = cat7132412)" instead of changing the actual title into the identifier

**Comment by lilimelgar** [comment]
This will be tested together with the new import of Desmet video metadata (to be done November 2017): issue #168
