### ISSUE TITLE
As a scholar, I would like to see the metadata labels of the fields of ALL the available collections in a user-friendly way without losing transparency

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#68]
This issue consists on implementing the approach followed for the labels of the B&G collection (#219) to all the other collections available in the MS.

As a minor issue, it is important to check consistency of the display of these labels in the different functions where they are used: Inspector and Search tools, sometimes they don't correspond.

OLD:
Change labels to "user-friendly" labels in the date fields? Query builder-Time selector. 

(See updated issue description at the end of this thread)

**Comment by lilimelgar** [comment]
Willem says: This is what the data gives. Replacing field names with user friendly names would already be a design decision. I guess it was decided to be close to the data?

**Comment by lilimelgar** [comment]
Yes, I added this to my requirement analysis ToDo list. Thanks!

**Comment by lilimelgar** [comment]
User says (April 4 workshop): Provide a legend of the meta data (how to read/understand what each field actually means - perhaps with a “?”. How do the trees in for example “Fields of type: date” relate?)

**Comment by lilimelgar** [comment]
Please notice that I moved this earlier since scholars need to consult this metadata. An initial solution can be to offer a simple pdf document...

**Comment by avlisodraude** [comment]
The issue has been done for parts 1 and 2. Part 3 is block for dependencies to be completed before development can be done. The work done is at the moment available only on development.
For the done part:
1. Change labels in the metadata inspector (e.g., "Fields of type: string" into something more meaningful for scholars, e.g.,: "Fields to create facets")
<img width="675" alt="screen shot 2017-08-07 at 16 21 21" src="https://user-images.githubusercontent.com/5918438/29031067-51b51c86-7b8d-11e7-97da-7715b981ce99.png">

2. Change labels that appear in the collection inspector, "field selector for collection analytics". An idea is to use the labels that come in the comparative search "facet builder"
![screen shot 2017-08-07 at 16 22 01](https://user-images.githubusercontent.com/5918438/29031099-66c65180-7b8d-11e7-9b5c-bc872e2e6dbe.png)

![screen shot 2017-08-07 at 16 21 51](https://user-images.githubusercontent.com/5918438/29031109-6d07d988-7b8d-11e7-9713-f15cf1ef5373.png)

![screen shot 2017-08-07 at 16 21 39](https://user-images.githubusercontent.com/5918438/29031119-729cc5e8-7b8d-11e7-832b-d4696507777a.png)

**Comment by lilimelgar** [comment]
This is a great improvement, thanks! 

It would be useful also to change the headers for "user-friendly" names, e.g.,:

- "Fields of type: date" : Metadata fields that specify dates
-"Fields of type: string": Metadata fields that can be used to create facet search (filters)
--"Fields of type: not_analyzed": Metadata fields that are not indexed (used for display only)
-"Fields of type: long": Metadata fields that indicate duration

These names have to be confirmed with Jaap before.

**Comment by lilimelgar** [comment]
**_This issue is split into three:_**

Here (issue #68) only (previous sub-issue no.2: Change labels that appear in the collection inspector, "field selector for collection analytics". An idea is to use the labels that come in the comparative search "facet builder.").

This issue is solved, but the suggestion was to include the labels starting not by the conceptual level (e.g., program), but using the name of the label (e.g., colour), as it was done before:

![screen shot 2017-07-13 at 16 05 10](https://user-images.githubusercontent.com/8133228/28170244-1779fca0-67e5-11e7-8103-dfd4dd00f9cf.png)

The other sub-issues are moved to issues:

**Comment by lilimelgar** [comment]
**_This issue is split into three:_**

1. sub-issue 1: Change labels in the metadata inspector (e.g., "Fields of type: string" into something more meaningful for scholars, e.g.,: "Fields to create facets") = #141 

2. sub-issue 2: this one "Change labels that appear in the collection inspector, "field selector for collection analytics". An idea is to use the labels that come in the comparative search "facet builder.")." Solved, but an improvement is suggested: to include the labels starting not by the conceptual level (e.g., program), but using the name of the label (e.g., colour), as it was done before:
![screen shot 2017-07-13 at 16 05 10](https://user-images.githubusercontent.com/8133228/28170244-1779fca0-67e5-11e7-8103-dfd4dd00f9cf.png)

3. New issue: #142

**Comment by avlisodraude** [comment]
@liliana: Parts of this issue have been done like: 
sub-issue 1: Change labels in the metadata inspector (e.g., "Fields of type: string" into something more meaningful for scholars, e.g.,: "Fields to create facets") = #141

The part that is not clear and might require some clarification is:

sub-issue 2: this one "Change labels that appear in the collection inspector, "field selector for collection analytics". An idea is to use the labels that come in the comparative search "facet builder.")." Solved, but an improvement is suggested: to include the labels starting not by the conceptual level (e.g., program), but using the name of the label (e.g., colour), as it was done before: <image>

Could you check what is missing ?

Regards,
Eduardo

**Comment by lilimelgar** [comment]
We have different options to display the metadata field labels. One option that was implemented before (graphic above) was:
-field name (in: schema:?)
Example: awards (in: bg:context)

The current solution in the Collection inspector and in the search recipes shows:
-Conceptual level => field name (in: description level)
Example: program => startdate (in: recordings)

The suggestion (what is missing to improve) is to go back to the previous way of displaying:
First the name of the field (sortdate, keyword, colour, etc.) and then add the extra information (i.e.: conceptual level, description level, ?).

This second solution is more user friendly.

However, this is not extremely urgent (not for October), since Eva is working on finding better user-friendly labels for all fields and adding snippets. Please hold this issue until November, I will update when we are ready for changes (I move it now to the end of the board).

**Comment by lilimelgar** [comment]
In summary:

The metadata fields of B&G collection have a specific structure, for example:

**bga:series.bg:production countries.bg:country**

these are the names of each element: 
bga: index (bg aggregated in this case)
series: conceptual level
bg: name space
production countries: broad field name
country: field name

The request is to show the labels in this order:
field name (in: index:conceptual level ->name space:broad field name)
The example above would be displayed like this:
**Country (in: bga:series ->bg:production countries)**

**Comment by lilimelgar** [comment]
Updated in a new issue: #403.
