### ISSUE TITLE
Check options to improve indexing (tokenization) for facet fields & prevent date periods from splitting into years

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#71]
Messy data in the "contributor" facet for this collection: Het Molukse perspectief in oorlogstijd. Also for this collection: IPNV (no stopwords. Also location facet for this collection shows some dates).

Add query->search with empty box->submit->see contributor facet

**Comment by lilimelgar** [comment]
Willem says:

[1] On the "contributor" facet: Sorry, but again (like in issue #70) this is the way ES indexes string fields like this one with standard analyzer. The raw data shows:
dc:contributor:Array[2]
0:"Wigard, Mw. Drs. W.H.M."
1:"Uneputty, Mw. I."
So exactly all these single words are indexed. Also, the initials are indexed, which of course doesn't make much sense, but ES standard analyzer doesn't know that. Also, some of these collections consist of only few records, so statistics (TF/IDF) doesn't really help here.

[2] On the IPNV and locations: This is caused by the fact that the dc records have a dc:coverage field, which (by definition) can contain bothe temporal and spatial values. The title for this field in the Facet selector (which is not a facet selector actually) should not be 'location'. An example value is:

dc:coverage:Array[5]
0:"Java"
1:"Batavia"
2:"Jakarta"
3:"Nederland"
4:"1945-1951"

You can see that value number 4 is providing temporal information (a period).

**Comment by roelandordelman** [comment]
@lilimelgar @wmelder I assume this issue can be closed or, if you want it lying around, ice it. Please find another EPIC then, because this is a search/indexing issue. The "finalize issues pending from v1" epic will be closed tomorrow.

**Comment by wmelder** [comment]
With the current mapping this is not an issue anymore...
Also it is required that a field is of type keyword field if it needs to appear in facets.
It is not expected that this issue will reappear.
