### ISSUE TITLE
Browser issue: adding collections in Internet explorer

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#74]
Can’t add collection in Internet Explorer 11 (feedback April 4)

**Comment by lilimelgar** [comment]
Also: Collection selector component is not loading selected collection in Chrome.

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #164](https://github.com/beeldengeluid/labo-components/issues/164) via [**ZenHub**](https://www.zenhub.com/)
