### ISSUE TITLE
Timeline: Max/Min dates disappear when sliding the timeline

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#75]
This input came from Werner (April 4 session) when using the Multilayered single collection search:
Used ‘recipe’ first > loss of selected timeline in search (see screenshots)
 Timeline > Max/Min dates disappear when sliding the timeline = loss of content
See also screenshots [here](https://docs.google.com/document/d/1EobXW7rmZ6niuCZexEYzRMsXKZdCBL3xmyTYnKuLc4A/edit#heading=h.lso8dpg1qnrs).

**Comment by whelmich** [comment]
@lilimelgar: You asked me what _Used ‘recipe’ first_ means. I don't know either as that specific line was written by Berber/Lora (an anonymous user in the Docs revision history). 

To clarify the bugs:

1. The timeline disappears when the resulting time range returns no results; there is no way to restore the time range.
2. When a time range is selected, the min/max dates at the start/end of the timeline disappear, so there is no indication of the total time range of result set.

**Comment by lilimelgar** [comment]
Thank you Werner! we will work on this soon...

**Comment by lilimelgar** [comment]
New user requests indicate that time slider should change for date picker #97

**Comment by lilimelgar** [comment]
Time slider was changed to date picker, and dates update properly.
