### ISSUE TITLE
Type/Filter/Auto-complete in metadata drop-down lists

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#76]
We should be able to type/filter/autocomplete in the metadata drop-downs in the Collection inspector recipe (both for date field and analysis field):

![screen shot 2017-07-26 at 09 47 55](https://user-images.githubusercontent.com/8133228/28610134-97209fb6-71e7-11e7-8420-7852f296dff0.png)

This drop-down menu (but with different labels) also appears when users add new facets (in the Comparative search and Multi-layered single collection search recipes), thus the search/filtering solution should be also added there:

![screen shot 2017-07-26 at 09 51 05](https://user-images.githubusercontent.com/8133228/28610273-0de3371c-71e8-11e7-9a83-79632db5ed95.png)

This suggestion comes from Werner (April 4 session):
(e.g. select2 js,  -- finding ‘keywords’ was just a matter of luck, hard work and time wasted. Select-filtering, add this to your js console when the collection inspector is active:
$('head').append('<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" /><script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>');$('select').select2();
// :)

This issue relates to the request for user-friendly labels for metadata fields (#68).

**Comment by avlisodraude** [comment]
A pull request has been created to address this issue at:
https://github.com/beeldengeluid/labo-components/pull/9

**Comment by lilimelgar** [comment]
Ok
