### ISSUE TITLE
As a user, I would like to be able to zoom in and out in a data chart, so I can explore data visually minimally per year and month

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#82]
Increase the granularity of time display in the time line chart and make it zoomable.
-Scale and zoom

(comes from Gitter) & user story 72: I want to be able to adjust the time period both by zooming into the timeline graph and as a separate filter.

For this we need the data not only per year, but also per day and month minimum.

See for instance this graphic (it needs month display when you only have one year):
![screen shot 2018-01-22 at 15 05 06](https://user-images.githubusercontent.com/8133228/35224563-ab53482c-ff85-11e7-9d36-1e5161cec63c.png)

**Comment by lilimelgar** [comment]
This issue needs important back-end work first (#415), users still request this (in workshops and summer school).

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labs-search-api #56](https://github.com/beeldengeluid/labs-search-api/issues/56) via [**ZenHub**](https://www.zenhub.com/)
