### ISSUE TITLE
Improve message "No results found" when there are no results

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#89]
In the cases when there are no results, the message should point the user to search tips. Improve message "No results found" by adding: "No results found. You can consult the search tips."

Search tips: to be done... (see issue #90)

**Comment by lilimelgar** [comment]
Instead of providing a customized message showing details of why or when there are no results (e.g., no search results for term X, date range X-Y), show a generic message indicating: There are no results for your search parameters. It is also useful to add a tooltip indicating what the search parameters were (e.g., as done in issue #440, showing the query composition/parameters.

**Comment by jblom** [comment]
@avlisodraude ok so just put in a generic message for all failed searches

**Comment by jblom** [comment]
Issue moved to [beeldengeluid/labo-components #183](https://github.com/beeldengeluid/labo-components/issues/183) via [**ZenHub**](https://www.zenhub.com/)
