### ISSUE TITLE
Implement the possibility to compose boolean queries

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#90]
About the **requirements for implementing boolean search**, I have done a quick check of the scholars’ needs in their demonstration scenario documents, and I see it is mostly about:

- Being able to use the basic operators (AND, NOT, OR). If possible, perhaps also proximity operators:
- these could be very interesting! NEAR, ADJ. 
- Other interesting proximity operator is: With (w): if your terms must be in the same order in which they are entered. Example: physical w1 therapy. Finds records where the word physical is listed first, followed by the word therapy, and where no more than one word separates the two terms.
- Support nesting (using long search strings with multiple boolean terms and parenthesis)
- Support using field names or codes to be used as limits for the operators. At this moment, the filter box allows filtering per cluster (all fields, titles, descriptions…), but sometimes they know exactly in what field(s) they would like to search in
- Truncation symbol and wildcard symbol
- Exact phrase (“ “)
- Does the order matter? it would be good to know that the operators are read in order from left to right, so they are sure in which order they are applied
- I suppose that when we have more automatic speech recognition text available, the “fuzzy” syntax for matching terms would be necessary, e.g., ?, ~
- A lot more advance, still to determine if necessary, would be to support using regular expressions (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html#regexp-syntax)

For the moment, the less urgent is 7 and 8. Please let me know if I should provide more input.

--
Old issue:
Users have requested to be able to construct Boolean queries in the query box.

Example (from Dream project demonstration scenario): 
In order to get as many mentions/hits of amphetamine as possible, we need a query that combines all existing spelling variations and brand names. As we are familiar with the topic, we are able to generate the following query:
    am*etami* OR wekami* OR benzedri* OR perviti* OR me*ylam*etami* OR isophan     OR neopharmedri* OR preludin* OR fencamfamin* OR actedron*

Users from M&M have also requested this.

This query does give results, but it is not clear why certain results do not correspond to the query.

**Comment by lilimelgar** [comment]
About the requirements for implementing boolean search, I have done a quick check of the scholars’ needs in their demonstration scenario documents, and I see it is mostly about:

Being able to use the basic operators (AND, NOT, OR). If possible, perhaps also proximity operators:
these could be very interesting! NEAR, ADJ. 
Other interesting proximity operator is: With (w): if your terms must be in the same order in which they are entered. Example: physical w1 therapy. Finds records where the word physical is listed first, followed by the word therapy, and where no more than one word separates the two terms.
Support nesting (using long search strings with multiple boolean terms and parenthesis)
Support using field names or codes to be used as limits for the operators. At this moment, the filter box allows filtering per cluster (all fields, titles, descriptions…), but sometimes they know exactly in what field(s) they would like to search in
Truncation symbol and wildcard symbol
Exact phrase (“ “)
Does the order matter? it would be good to know that the operators are read in order from left to right, so they are sure in which order they are applied
I suppose that when we have more automatic speech recognition text available, the “fuzzy” syntax for matching terms would be necessary, e.g., ?, ~
A lot more advance, still to determine if necessary, would be to support using regular expressions (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html#regexp-syntax)

For the moment, the less urgent is 7 and 8. Please let me know if I should provide more input.

**Comment by lilimelgar** [comment]
About the **requirements for implementing boolean search**, I have done a quick check of the scholars’ needs in their demonstration scenario documents, and I see it is mostly about:

Being able to use the basic operators (AND, NOT, OR). If possible, perhaps also proximity operators:
these could be very interesting! NEAR, ADJ. 
Other interesting proximity operator is: With (w): if your terms must be in the same order in which they are entered. Example: physical w1 therapy. Finds records where the word physical is listed first, followed by the word therapy, and where no more than one word separates the two terms.
Support nesting (using long search strings with multiple boolean terms and parenthesis)
Support using field names or codes to be used as limits for the operators. At this moment, the filter box allows filtering per cluster (all fields, titles, descriptions…), but sometimes they know exactly in what field(s) they would like to search in
Truncation symbol and wildcard symbol
Exact phrase (“ “)
Does the order matter? it would be good to know that the operators are read in order from left to right, so they are sure in which order they are applied
I suppose that when we have more automatic speech recognition text available, the “fuzzy” syntax for matching terms would be necessary, e.g., ?, ~
A lot more advance, still to determine if necessary, would be to support using regular expressions (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html#regexp-syntax)

For the moment, the less urgent is 7 and 8. Please let me know if I should provide more input.

**Comment by jblom** [comment]
Alright, now there is a first implementation of this working on the test environment (I've only updated the search API so far).

Now the search API detects when a user does a boolean/wildcard query by looking for the keywords: OR, NOT, AND, * or ?

Whenever one of these is in the entered search terms, everything is interpreted by a proper boolean/wilcard interpreter (also taking into account the selected fields).

By the way: this also supports what you call 'nesting', e.g.

(koe AND varkens) OR boeren

The proximity parameters is also supported in a way by ES, but we'll have to come up with a syntax for that. This one should not be too hard to incorporate too. 

The field specific queries now interfere with the field selector a bit, so we also should think a bit about if we want to support this right away. Also we have the issue that field names are very long and are currently even hidden for the user (so it involves quite something to build in a user friendly manner).

**Comment by jblom** [comment]
Just to mention: I've tested the "drugs query" as well. It works.

**Comment by lilimelgar** [comment]
Great! Tested! As for the field specific queries, in which way do they interfere with the field selector?
