### ISSUE TITLE
Add number of hits (obtained from issue 136) to time line chart on mouseover

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#91]
Adapt the timeline chart used in the Collection inspector and Comparative search recipes to display display the total number of results in each point of the graphic:

![screen shot 2017-10-12 at 16 28 00](https://user-images.githubusercontent.com/8133228/31501365-5901f782-af6a-11e7-8ca5-290eb5f33b5c.png)

**Comment by jblom** [comment]
Currently the absolute **total** number of hits per year is not available in the data returned from the search API. This needs to be added in order for this issue to be solved. Maybe create a separate issue for this?

**Comment by lilimelgar** [comment]
Sure, see issue #136

**Comment by lilimelgar** [comment]
@avlisodraude This issue seems to be solved now, shall I close it? I tested in master and works well for absolute values. Relative values are still missing: see other issues: #136 and #156

**Comment by lilimelgar** [comment]
Ready for B&G collection, pending to check for other collections when issue #155 is solved.

**Comment by lilimelgar** [comment]
Tested with available collections in Version 2, pending to test with Desmet (film and posters) since date fields have not been indexed yet. Closed for now.
