### ISSUE TITLE
Highlight search term in search result snippet

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#93]
The term entered in a query should be highlighted in the result snippet:
![screen shot 2017-07-20 at 11 38 11](https://user-images.githubusercontent.com/8133228/28411067-f830b0ea-6d3f-11e7-8519-45287d1c5962.png)

 and also in the metadata display in the "detailed result viewer":

![screen shot 2017-07-20 at 11 41 40](https://user-images.githubusercontent.com/8133228/28411232-6f8313fe-6d40-11e7-85c3-7a8e2388a783.png)

**Comment by lilimelgar** [comment]
Tested in the master (March 28), it highlights the search term when this is only one term. I added another issue for highlighting terms when there are more than one in the query expression. #346

**Comment by jblom** [comment]
@lilimelgar true, it does highlight the whole phrase though, but not each word individually.
