### ISSUE TITLE
Add description to recipes

### ISSUE THREAD

**Issue by lilimelgar** [CLARIAH/wp5_mediasuite#94]
This is static content describing what this recipe does. This content is currently shown in the [main recipe page](http://mediasuite.clariah.nl/recipes). But when the user clicks on the recipe, this information is not displayed. 

Please add updated version of the text [HERE ](https://docs.google.com/document/d/1yL_EEnW9_8tYX7IpHMbae2c1ETnsXYR238Cqm7Xwdpk/edit#heading=h.8zhrp9ypln4v)to this part of the interface for the Collection inspector recipe:
![screen shot 2017-08-31 at 14 15 32](https://user-images.githubusercontent.com/8133228/29922676-e24e7f18-8e56-11e7-9a24-9be13fb48324.png)

Please do the same for the Comparative search recipe ([text here](https://docs.google.com/document/d/1yL_EEnW9_8tYX7IpHMbae2c1ETnsXYR238Cqm7Xwdpk/edit#heading=h.z077yc3zlsl7))
and the Single Collection search recipe, ([text here](https://docs.google.com/document/d/1yL_EEnW9_8tYX7IpHMbae2c1ETnsXYR238Cqm7Xwdpk/edit#heading=h.1xihjnir2pzw))

**Comment by lilimelgar** [comment]
This is done for the Collection inspector recipe, all OK. Could you please do the same for the Single collection search and the Comparative search? the texts are in the same file above. Thanks.

**Comment by avlisodraude** [comment]
Description for recipes added and merged into master. 
Modified files:
collection-inspector.json, single-search.json.
What was done to the files?
New key/value pair to include recipeDescription to them.

**Comment by lilimelgar** [comment]
All OK! we may add help texts later, but this works well for now :)
